### ISSUE TITLE
openssl config failed error on sfdx force:source:retrieve

### ISSUE THREAD

**Issue by chandra2ravi** [forcedotcom/salesforcedx-vscode#1027]
I'm getting below error on every sfdx command

![image](https://user-images.githubusercontent.com/93057/52491018-bfcf6780-2b8b-11e9-99ac-c2b1a1308c66.png)

**Comment by allileong** [comment]
Hi @chandra2ravi, thanks for reporting this issue. Looking into it now.

**Comment by allileong** [comment]
Hi @chandra2ravi, this looks to be a problem caused by the OPENSSL_CONF environment variable being set to an invalid value. 

Could you try unsetting the environment variable, or setting it to a valid filepath? 

Here are some resources on how to unset the environment variable or how set it to a valid path:
https://github.com/npm/npm/issues/17261
https://github.com/openssl/openssl/issues/3764

**Comment by chandra2ravi** [comment]
I removed from environment variable but still same error.

**Comment by allileong** [comment]
Hi @chandra2ravi, are you still experiencing this issue?

**Comment by chandra2ravi** [comment]
I uninstalled open ssl due to the slowness of vscode.

**Comment by allileong** [comment]
Hi @chandra2ravi , thanks for letting me know. I'm going to close out this bug for now, but please feel free to reopen it if you encounter this issue again in the future.

**Comment by nitssnatha** [comment]
I am still facing this issue.
openssl config failed: error:02001003:system library:fopen:No such process
ERROR running force:auth:jwt:grant:  error:2006D080:BIO routines:BIO_new_file:no such file
