### ISSUE TITLE
Clicking defaultScratchOrgName in bottom bar prompts for default org settings

### ISSUE THREAD

**Issue by Szandor72** [forcedotcom/salesforcedx-vscode#1044]
I used to open my default scratch org by clicking its name in the bottom bar. 

![image](https://user-images.githubusercontent.com/16804218/52640753-8d00d880-2ed7-11e9-8b92-24fda7b8586f.png)

When I click it after this weekend's updates, I am prompted (after several seconds) to select a default org. 

![image](https://user-images.githubusercontent.com/16804218/52640888-e23cea00-2ed7-11e9-90f3-d573ae522c97.png)

the config:set commands runs after I select an Org but nothing else happens. no org is opened.

Workaround: using the 'org open' command from ctrl+p works without issues. 

current win10, dx and vs code installations.

**Comment by msrivastav13** [comment]
The browser symbol next to the name opens the default org for me or runs that sfdx force:org:open

**Comment by lcampos** [comment]
@Szandor72 The latest release includes a new feature called [Org Picker](https://github.com/forcedotcom/salesforcedx-vscode/issues/944) (# 2 in attached screenshot). This allows you to open a command palette menu to switch between the orgs you've authenticated to. Knowing some people used the footer button to open their default org, we decided to keep that functionality by leaving the browser icon  (# 1 in attached screenshot) but remove the text/org name that used to be part of it since that had to be part of the Org Picker functionality.

Is this not the behavior you're seeing ?
![org_picker](https://user-images.githubusercontent.com/1041842/52682921-f859a300-2ef5-11e9-9a8d-35d1fca203b2.png)

**Comment by Szandor72** [comment]
It's a feature, not a bug! Classic! Thank you!
