### ISSUE TITLE
Converted source not pushing to scratch orgs

### ISSUE THREAD

**Issue by chandra2ravi** [forcedotcom/salesforcedx-vscode#1137]
i used source convert an try to push to scratch org and getting below error 

![Screen Shot 2019-03-10 at 9 58 12 AM](https://user-images.githubusercontent.com/93057/54086842-56be4980-431b-11e9-8dbc-68b3acabc407.png)

**Comment by ntotten** [comment]
There are errors reported in the push. It looks like the metadata for a customobject is invalid.

**Comment by chandra2ravi** [comment]
@ntotten  check the path in error file it's saying force-app/main/default/Game__C there is no direct file

**Comment by ntotten** [comment]
@lcampos See the path to this. Is this a bug in how we are printing the error messages? Notice the folder `classes` is missing.

**Comment by lcampos** [comment]
I haven't been able to replicate this issue. I think this might be an issue with the object metadata missing some details. I don't think this is an issue with the `force:mdapi:convert` command since I ran this on a project and was then able to deploy it using `source:push`.

@chandra2ravi can you confirm your project's objects can be successfully deployed to an empty org using normal metadata api ? Did you manually tweak any of those object's metadata before running `force:mdapi:convert` ? Or were all the objects retrieved using the metadata api and then converted to sfdx ?

**Comment by chandra2ravi** [comment]
I didn't teak any but the first time it deployed the second org failed.

**Comment by lcampos** [comment]
Can you provide a code sample we can use to replicate the issue on our side ? We are not able to replicate it with the projects we are testing with.
