### ISSUE TITLE
Deploy Source in Manifest to Org response does not appear in problem tab

### ISSUE THREAD

**Issue by SalesforceBobLightning** [forcedotcom/salesforcedx-vscode#1146]
### Summary

When I use the `Deploy Source in Manifest to Org` command pallette or right click option on a manifest file, errors are not displayed in either the output tab or problem tab

### Steps To Reproduce:

1.  Right click on a manifest file and select `Deploy Source in Manifest to Org`

### Expected result

Errors should appear in the problem tab

### Actual result

No response displayed anywhere

**VS Code Version**: 

Latest

**SFDX CLI Version**:

Latest

**OS and version**:

Window 10

**Comment by brpowell** [comment]
Hi @SalesforceBobLightning. We're working on reproducing this issue but haven't had any luck yet. If you create a simple manifest with one component that has issues, do you still get no results?

**Comment by SalesforceBobLightning** [comment]
Hi @brpowell 

Thanks for investigating.

To reproduce, you will need code which has issues and would fail to deploy.

**Comment by brpowell** [comment]
Happy to do so @SalesforceBobLightning. Do you have piece of code I can try it out with? When I attempt to deploy an apex class with failures the problems surface as expected.

**Comment by nicocrm** [comment]
Hi @brpowell, I have the same issue on one of my environments, and another one that works fine.  The OS that has the problem is on MacOS and Code version 1.32.3, the OS that works is on Linux, but the org being worked on is the same in both cases, so it does not appear to be related to the code.
Is there a way that I can capture more information about the problem that would give you context?  If I copy and paste the command from the "output" window to the terminal window, it works fine (and shows the errors).  But nothing shows in the Output window (other than "... ended with exit code 1") or in the Problems window.

**Comment by nicocrm** [comment]
More mysterious, I renamed the project folder without making any change, opened the renamed version, and then it was working fine.  So it appears somewhere in the bowels of vscode or sfdx some setting was toggled to prevent the problems capture on that specific folder path.
