### ISSUE TITLE
When I do SFDX: Retrieve from source - I get "No results found"

### ISSUE THREAD

**Issue by m0gul** [forcedotcom/salesforcedx-vscode#1293]
I've set everything up from scratch about 5 times to try and get this working, but I'm at a loss. I have the default org connected / authorized and I see the folder structure on the left, but when I try to right-click any folder (aura for example), then go to "SFDX: Retrieve Source From Org", I get:

"=== Retrieved Source
No results found"

In the output folder. Any assistance would be greatly appreciated, thanks!

**Comment by lcampos** [comment]
Hi @m0gul, the retrieve command will only retrieve metadata for the existing files if you are triggering it from a folder. E.g. if you do `SFDX: Retrieve Source From Org` from an empty folder, then it won't bring anything from the org since there is no metadata in your folder.

If you're looking at downloading metadata that you still don't have on your computer then you can try downloading it by triggering the retrieve command using a `package.xml`. If you create a project using `SFDX: Create Project With Manifest` you'll get a `manifest` folder with a pre-defined `package.xml` that you can use once you've authenticated to your org.

**Comment by lcampos** [comment]
Please confirm you are able to retrieve the metadata using the package.xml approach and that the folder you are using for triggering the retrieve command is not empty.

**Comment by suraj07081995** [comment]
I faced the issue: "=== Retrieved Source
No results found"
write click on **package.xml** under **manifest** click on SFDX: Retrive Source in Manifest from Org.
Now all the classes will be retrieved

**Comment by DenverDoug** [comment]
Why is this an option for things that won't work?!  Please add an message beyond "No Results Found" that you "May want to try this command by right-clicking on the package.xml file".... 😡

**Comment by suraj07081995** [comment]
> Why is this an option for things that won't work?! Please add an message beyond "No Results Found" that you "May want to try this command by right-clicking on the package.xml file".... 😡

correct, next time when it occurs i will follow up!

**Comment by christluo** [comment]
Hello, i ran into the exact same issue here. When I right clicked package.xml to click SFDX: Retrieve Source in Manifest from Org, I got "No results found". As this is my first time to download the xml file from the Org I do not have anything exist in the folder. How should I make this work? Please help!

**Comment by deepak-kenkere** [comment]
i too have the same issue. i tried to retrieve with manifest on the package.xml file but no files retrieved

**Comment by ybiyani** [comment]
Trying to retrieve the source using package.xml and get 
=== Retrieved Source
No results found

**Comment by sashitol** [comment]
check package.xml version tag and see if it has right version     <version>48.0</version>

**Comment by ceciquin** [comment]
I have a question: It's possible to retrieve all the specification related to all the profiles and a specific customObject? example: fields available in all profiles  for each field in Campaign Member.

Thanks!

Ceci.
