### ISSUE TITLE
Specify template error on creation manifest project

### ISSUE THREAD

**Issue by Antonyjay** [forcedotcom/salesforcedx-vscode#1324]
### Summary

I am creating a new project with manifest for the first time. When I try to create a new project with manifest I get the error that I need to specify a template. (see screenshot for output)

### Steps To Reproduce:

1.  Ctrl+Shift+P on Windows and select SFDX: Create Project with Manifest.
1.  Enter a project name and select a folder and run

### Expected result

I would expect that a new project is created

### Actual result

I receive an error in the output saying I need to specify a template

### Additional information

Screenshot:
![image](https://user-images.githubusercontent.com/22470358/57450323-719b3480-725e-11e9-9922-18b7c0fbbb2e.png)

**Comment by lcampos** [comment]
Hi @Antonyjay, I think this might be caused by you being on an old Salesforce CLI version. Can you open your terminal and run `sfdx --version` to see in which version you are on ? The latest version is 7.5.0. If you are in version 6.x.x or below, you can run `sfdx update` and re-running `SFDX: Create Project with Manifest` should work.

**Comment by Antonyjay** [comment]
Thanks, this solved the issue
