### ISSUE TITLE
Peek/go to definition not showing on right click.

### ISSUE THREAD

**Issue by risseno** [forcedotcom/salesforcedx-vscode#1357]
### Summary

It also doesn't work using keyboard shortcuts. My normal way of accessing my sfdc metadata in VS cod File-->open folder-->select the folder that i have my entire SFDC meta data stored in (pulled via xml manifest). if i then opened an apex class i used to be able to highlight a class name and go to/peek definition and it would show me the definition. On pretty much everything i would show me some type of definition. Now the option to do so is gone, all that remains is:

Change all occurances
cut
copy
past
command pallete

I recently saved that entire folder as a workspace, and it didn't help.

This was a sudden change, one day it worked then after i restarted my computer it stopped working.

![vs](https://user-images.githubusercontent.com/47830790/58118445-af308380-7bb5-11e9-8637-1c120dd6cc1c.PNG)

**VS Code Version**: 1.34

**SFDX CLI Version**: Latest version (assuming) i just installed the salesforce extension pack three weeks ago after getting a new work PC. EDIT: 45.15.1

**OS and version**: windows 10 enterprise version 1709 ( OS Build 16299.461)

**Comment by lcampos** [comment]
Hi @risseno , thanks for opening this issue. At a first glance there are 2 things I think could be happening here, the first being that Java configuration is missing. That's needed in order for the extensions to run the Apex Language Server, which is what provides the info for those features. If that's the case you can follow the instructions in our article [Set Your Java Version](https://forcedotcom.github.io/salesforcedx-vscode/articles/troubleshooting#set-your-java-version).

It could also be that the class you are working on is not entirely being compiled by the Apex Language Server because it has dependencies with SObjects. You can fix this by running `SFDX: Refresh SObject Definitions` command from the command palette.

Can you let us know if any of those options fixed your issue ?
cc @praksb

**Comment by praksb** [comment]
@risseno It looks like the Apex language server didn't start. Can you follow the instructions that @lcampos mentioned previously to set the java version?
