### ISSUE TITLE
Add ability to suppress distracting language server output

### ISSUE THREAD

**Issue by joeferraro** [forcedotcom/salesforcedx-vscode#1429]
**Is your feature request related to a problem? Please describe.**
It's frustrating when the Apex Language Server, for example, experiences an exception and it prompts VSCode to focus the Output panel with information that isn't helpful to the Salesforce developer

**Describe the solution you'd like**
Implement `RevealOutputChannelOn` to suppress VSCode from focusing Output

**Additional context**
Examples: 
https://github.com/angular/vscode-ng-language-service/pull/195
https://github.com/rust-lang/rls-vscode/blob/master/src/configuration.ts#L9

**Comment by lcampos** [comment]
Hi @joeferraro this is a good idea. Do you mind sharing a piece of code that causes the issues you mentioned ? We use test projects that cause compile issues but I haven't seen this behavior of the error causing an Output panel focus.

**Comment by sc5148** [comment]
@lcampos Here is a [video](https://www.dropbox.com/s/h6k9fhosjhdmipj/VSCODE%20bug.mp4?dl=0) I posted on #1356 . I want to suppress opening the output panel everytime. Also, instead of opening the output window, a popup can be shown to the right side bottom of the screen if the operation was successful.

**Comment by joeferraro** [comment]
I still experience this issue on a regular basis
