### ISSUE TITLE
Duplicated sfdx:deploy commands on v46.4.0

### ISSUE THREAD

**Issue by ayanozturk** [forcedotcom/salesforcedx-vscode#1457]
### Summary

On save, sfdx:deploy is triggered multiple times.

### Steps To Reproduce:

1.  Open any SF class to edit
1.  Make a change and save - notice terminal log running sfdx deploy:apex command once
1.  Make another change and save - notice terminal runs same command twice
1.  Make another change and save - notice terminal runs same command 3 times
1.  to infinity and beyond

### Expected result

Should trigger deploy only once on save

### Actual result

Multiple deploys / slow process / eventual failure

### Additional information

**VS Code Version**: Version 1.36.0 (1.36.0)
**SFDX CLI Version**: sfdx-cli/7.12.3-bfc421fa08 darwin-x64 node-v10.15.3
**OS and version**: Mac OS Mojave 10.14.5

I can replicate this on Salesforce Extension Pack v46.4.0
When I revert back to v46.3.0 it works correctly.

**Comment by brpowell** [comment]
Hi @ayanozturk. I'd like to clarify what exactly you're seeing:

This clip is the expected behavior - deploy on save is now faster, so multiple saves to the same file will be queued up for sequential deploying. Or if I save a file let's say 5 times before the previous deploy is done, all those changes will be grouped together for another deploy.
![expected](https://user-images.githubusercontent.com/10779873/60907445-66e52780-a22e-11e9-83ea-6fed12727461.gif)

This clip is undesired behavior - saving a file multiple times will kick off deploys regardless if another one is running or not. The deploys "stack" instead of waiting for the previous to finish.
![unexpected](https://user-images.githubusercontent.com/10779873/60907598-cba08200-a22e-11e9-9736-2e0a9dab79fc.gif)

Which one is the experience you're having?

**Comment by ayanozturk** [comment]
@brpowell neither.

I'm was seeing "stacked" deployments on single save action. 
- open a file
- save and wait -> observe 1 deploy -> wait for finish
- save and wait -> observe 2 "stacked" deploy -> wait all of them to finish
- save and wait -> observe n "stacked" deploy -> wait all of them to finish
- save and wait -> observe n +1 "stacked" deploy -> wait all of them to finish
...

This behavior was with extension version v46.4.0

After upgrading to v46.5.0 today, I don't see this bug anymore.

**Comment by brpowell** [comment]
Glad the behavior has been fixed, thanks for the report @ayanozturk. Let us know if you see any other issues.
