### ISSUE TITLE
Deploy on Save not working

### ISSUE THREAD

**Issue by alankipalle** [forcedotcom/salesforcedx-vscode#1525]
### Summary

Deploy on Save is not working in spite of setting is enabled in the Setting file.

### Steps To Reproduce:

1.  Open Apex class in VS code
2.  Modify and save it.

### Expected result

Expected to be saved automatically without doing deploy to org command

### Actual result

It is no saving to org.

### Additional information

_Feel free to attach a screenshot
![image](https://user-images.githubusercontent.com/41838876/62298659-6dd41400-b441-11e9-85b1-d8bde5cf3aa9.png)
_.

**VS Code Version**:
1.36.1
**SFDX CLI Version**:
7.15.3-c7d407d236
**OS and version**:
Windows 10

**Comment by ntotten** [comment]
Please pro
In order to diagnose this issue we will need more information. Please provide the following.

* Logs(See: https://github.com/forcedotcom/salesforcedx-vscode/wiki/How-to-Collect-Performance-Information-for-Support)
* List of all Visual Studio Code extensions installed and the Versions (Run the command `code --list-extensions --show-versions`)
