### ISSUE TITLE
Mismatch of xml namespace in Aura component bundles before/after save

### ISSUE THREAD

**Issue by steals** [forcedotcom/salesforcedx-vscode#1550]
### Summary

All new Aura component created through VSCode has `urn:metadata.tooling.soap.sforce.com` xml namespace by default. But when the component is saved to the org and then retrieved the xml namespace is changed to `http://soap.sforce.com/2006/04/metadata`.

### Steps To Reproduce:

1.  This is step 1. Create Aura Component and deploy it to the org
1.  This is step 2. Retrieve component bundle from the org

### Expected result

Namespace should remain the same.

### Actual result

namespace is changed from `urn:metadata.tooling.soap.sforce.com` to `http://soap.sforce.com/2006/04/metadata`.

![Screen Shot 2019-08-09 at 18 25 49](https://user-images.githubusercontent.com/682252/62790851-a2486f80-bad4-11e9-994c-0183a58d4679.png)

**Comment by lcampos** [comment]
Hi @steals this has been fixed in the latest versions of the Salesforce CLI. The old versions of the CLI would add `urn:metadata.tooling.soap.sforce.com` when creating metadata using the CLI create commands but that was not in line with what the server would return.

I'll be closing this issue now but let us know if you have any other question on this, thanks for opening this issue.
