### ISSUE TITLE
Records are not visible during debugging when records count is greater than 8. Getting message as tooltip

### ISSUE THREAD

**Issue by ArunSahu1992** [forcedotcom/salesforcedx-vscode#1639]
### Summary

Records are not visible during debugging when records count is greater than 8. Getting message as tooltip "'List of size 18 too large to display".

### Steps To Reproduce:

1. Set up debugger at Apex class which has List<Sobject> with length greater than 10.

### Expected result

All 18 records should display.

### Actual result

"'List of size 18 too large to display".

### Additional information

Image has been attached. 
![bug](https://user-images.githubusercontent.com/31402954/64519997-d6e95a00-d312-11e9-8432-71502f5ef352.png)

**VS Code Version**:
   **1.38**
**SFDX CLI Version**:
**43.13.0**
**OS and version**:

**Comment by lcampos** [comment]
That is correct, if you want to get all the data for structures like List, Map, Set, etc using Replay Debugger then you need to use a checkpoint instead of a breakpoint. 

After you enable the Replay Debugger (`SFDX: Turn On Apex Debug Log for Replay Debugger`) you'll have to run `SFDX: Toggle Checkpoint` in the lines you want the detailed info for, then `SFDX: Update Checkpoints in Org` and rerun your the Apex code you're debugging.

Section `Set Breakpoints and Checkpoints` in the [Apex Replay Debugger](https://forcedotcom.github.io/salesforcedx-vscode/articles/apex/replay-debugger) docs has more details on this.

**Comment by ArunSahu1992** [comment]
Thanks it worked for me.
