### ISSUE TITLE
Refresh sobject definitions fails behind https proxy

### ISSUE THREAD

**Issue by strotto** [forcedotcom/salesforcedx-vscode#1653]
### Summary

Refresh sobject definitions from Sandbox while behind a https proxy fails with the exit code 1 and the message "Error: self signed certificate in certificate chain".
I have defined the certificate in the environment variable NODE_EXTRA_CA_CERTS, and am able to retrieve and deploy.

### Steps To Reproduce:

1.  Use a network with https proxy
2.  Save the network certificate locally
3.  Create the environment variable NODE_EXTRA_CA_CERTS pointing to the locally saved certificate
4.  Perform a Refresh Sobjects Definitions

### Expected result

Sobject definitions should be retrieved

### Actual result

Action fails with error "Error: self signed certificate in certificate chain"

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.37

**SFDX CLI Version**: 7.8.1

**OS and version**: Windows 10 1803

**Comment by ntotten** [comment]
Unfortunately, there isn't a lot we can do here to help out. If you have already followed the [instructions here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_firewall.htm), which it sounds like you have. Generally, the issue is something that you will have to work out with your IT department.

**Comment by strotto** [comment]
hi @ntotten, I was initially getting this error on all commands but after adding the cert details it resolved the issue for the retrieve/depoy commands but not for this one. I don't think the issue is with my IT department since this error is only happening for some commands.
