### ISSUE TITLE
Error while Retrieving Source from Org using VS code

### ISSUE THREAD

**Issue by vjlourdu** [forcedotcom/salesforcedx-vscode#1658]
Hi,

I am getting below error while trying to retrieve Source from the Org. Please help me fixing the same.

15:01:43.512 sfdx force:source:retrieve --manifest c:\Users\username\Downloads\Salesforce\LWC\LWC\manifest\package.xml
ERROR running force:source:retrieve:  Invalid or unsupported zip format. No END header found
15:03:17.260 sfdx force:source:retrieve --manifest c:\Users\username\Downloads\Salesforce\LWC\LWC\manifest\package.xml ended with exit code 1

Followed this issue and not able to solve it and there is no space in the manifest path as well.
https://github.com/forcedotcom/salesforcedx-vscode/issues/1423

SFDX Version:sfdx-cli/7.23.1-ced0ec4940 win32-x64 node-v10.15.3

VSCODE Version : 1.30.2

OSVersion: Windows10

**Comment by vjlourdu** [comment]
I am able to solve the problem after removing the  below mentioned StaticResources from Package.xml file. This is the one which is causing this problem.
<types>
        <members>*</members>
        <name>StaticResource</name>
    </types>

**Comment by lcampos** [comment]
Hi @vjlourdu, I'm assuming you are using `SFDX: Retrieve Source in Manifest from Org` based on the data you provided. I think the issue is not necessarily with retrieving StaticResources but with the size of the retrieve. I've been able to retrieve StaticResources successfully using a manifest and a non-scratch org. I think what's happening here is that the zip file for you're retrieving is too big, the transaction times out and you end up with the `Invalid or unsupported zip format. No END header found` error.

Could you try retrieving only StaticResources or just one of them to see if what I'm saying is actually what you are running into ?

**Comment by christianortega123** [comment]
Hello @lcampos, I have tried only retrieving part of my original (very large) package.xml file and it worked. It does indeed look like it is a size problem. Do you think there's a workaround so that I can retrieve everything from my XML file? Thanks.

**Comment by christianortega123** [comment]
Please reopen

**Comment by lcampos** [comment]
@christianortega123 the CLI uses the Metadata API for retrieves and deploys. The API itself has limits on the size and number of the files that can be retrieved at once. Can you tell us how many files or the size of the zip file you are trying to retrieve ? We'd like to confirm the issue is with running into Metadata API limits and not with something else.
