### ISSUE TITLE
New Custom Objects are not retrieved

### ISSUE THREAD

**Issue by evanmcd** [forcedotcom/salesforcedx-vscode#1690]
### Summary

New Custom Objects are not retrieved when running the Retrieve Source from Org command on the objects folder.

### Steps To Reproduce:

1.  Create a new Custom Object in a sandbox
1.  With VS Code connected to that sandbox org, right click on the force-app/main/default/objects folder and choose Retrieve Source from Org

### Expected result

The new Custom Object should appear in the source files list

### Actual result

The new Custom Object does not appear in the source files list

### Additional information

**VS Code Version**: 1.38.1

**SFDX CLI Version**: 7.23.1-ced0ec4940 darwin-x64 node-v10.15.3

**OS and version**: OS: Darwin x64 18.7.0

**Comment by lcampos** [comment]
Hi @evanmcd, thanks for opening this issue. Currently, running a retrieve by right clicking a folder would only retrieve the metadata that's already part of that folder. Having said that, have you tried using the new Org Browser in order to retrieve metadata for your org [Org Browser](https://developer.salesforce.com/tools/vscode/articles/user-guide/org-browser) ?

**Comment by evanmcd** [comment]
Hey @lcampos, thanks so much for this. I hadn't thought of using the Org Browser, and it worked great.

**Comment by diyer** [comment]
Closing this as this is WAD.
