### ISSUE TITLE
Error 'path does not exist' on SFDX Create Project

### ISSUE THREAD

**Issue by ZachLucasDev** [forcedotcom/salesforcedx-vscode#1797]
### Summary

When ever I create a new project in VS code I am greated with this error 
"The path 'c:\sfdx\HelloWorldLightningComponet' does not seem to exist anymore on disk."

### Steps To Reproduce:

1.  Installed https://sfdc.co/sfdx_cli_win ( Have also tried the 64bit version)
2. Added Extensions Salesforce CLI Intergration and Salesforce Extension Pack
3. Ctl+Shit+P
4. SFDX create new project
5. Select standard 
6. Enter Project name
7. press enter

### Expected result

A new project to be created

### Actual result

Error "The path 'c:\sfdx\HelloWorldLightningComponet' does not seem to exist anymore on disk."

**VS Code Version**: 1.40.0

**SFDX CLI Version**: sfcx-cli/7.32.0-b30e0302f0 win32-x64 node-v10.15.3

**OS and version**: Window 10 version 1903

**Comment by lcampos** [comment]
Hi @ZachLucasDev thanks for opening this issue. Are you trying to create the project inside of a folder that's backed up by OneDrive or another file syncing product ?

**Comment by ZachLucasDev** [comment]
No I did not. I was attempting to create it directly off my C drive which is not backed up. One drive is disabled

**Comment by pashquest** [comment]
Hi @ZachLucasDev - It might not concern you anymore but it maybe it helps someone else. I had the same issue and could fix it by installing the correct CLI Version for my PC. Accidently i have installed the CLI Windows 32-Bit version instead of CLI Windows 64-Bit. Steps: 
1) uninstall your existing sfdx CLI version. 
2) Remove Saleforce CLI from your Path environment variables
3) Download&Install the correct sfdx CLI version for your PC (32bit or 64bit)
4) Good Luck !

**Comment by ZachLucasDev** [comment]
Tha k's @pashquest however, that was the very first thing I tried back then. I haven't attempted to trouble shoot this for awhile now.

**Comment by pavandambalappa** [comment]
Thanks @pashquest : I struggled for almost 3 hours. By mistake I installed 32-bit CLI version rather than 64-bit. I multiple times uninstalled 32 bit and installed 64 bit CLI. But I forgot to remove from path variables. 

I Followed below steps it worked.

1. Uninstalled 32-bit CLI.
2. Removed Path variable under  **"Select Start, select Control Panel. double click System, and select the Advanced tab. Click Environment Variables. In the section System Variables, find the PATH environment variable and select it."**
3. Re-installed 64-bit CLI. It worked.

**Comment by Tojom25** [comment]
When installing the CLI, leave "Set path to Salesforce CLI" unchecked.

**Comment by sncardonam** [comment]
Thanks @pavandambalappa that worked for me.

**Comment by SegmentSFDC** [comment]
After a lot of heartburn, I was running VS code in user perspective( windows concept not the salesforce user concept) right click and run as Administrator when you launch VS code ( MKdir permission was turned to read and write was not provided at my windows user level)

**Comment by jay1310** [comment]
> Hi @ZachLucasDev - It might not concern you anymore but it maybe it helps someone else. I had the same issue and could fix it by installing the correct CLI Version for my PC. Accidently i have installed the CLI Windows 32-Bit version instead of CLI Windows 64-Bit. Steps:
> 
> 1. uninstall your existing sfdx CLI version.
> 2. Remove Saleforce CLI from your Path environment variables
> 3. Download&Install the correct sfdx CLI version for your PC (32bit or 64bit)
> 4. Good Luck !

Hey, Thanks a lot... I had also installed 32bit version by mistake.
