### ISSUE TITLE
Retrieve Source from Org returns "No results found"

### ISSUE THREAD

**Issue by ybiyani** [forcedotcom/salesforcedx-vscode#1834]
### Summary

Retrieve Source from Org returns "No results found"

### Steps To Reproduce:

1. Create a new project using Create Project with Manifest

2. Right click package.xml -> Retrieve source from org and  it fails with 
Error deploying or retrieving source: The file or directory that you tried to deploy or retrieve isn't in a package directory that's specified in your sfdx-project.json file. Add this location to your "packageDirectories" value, or deploy or retrieve a different file or directory. For details about sfdx-project.json, see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm
3. Updated sfdx-project.json as follows 

{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    },
    {
      "path": "manifest" 
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "47.0"
}

4. Right click package.xml -> Retrieve source from org and  it shows 
=== Retrieved Source
No results found

### Expected result

This is a brand new project so expecting files to downloaded! 

### Actual result

=== Retrieved Source
No results found

**Comment by dv297** [comment]
I am relatively new to using SalesForce DX and this extension, so I think the issue you are having is a misunderstanding of the "Retrieve Source From Org" command that I also had. That command is only applicable to when you already have code from your org downloaded and available on your local machine/ already in your VS Code project. It does not retrieve the code for the first time.

The command you (and others) may be looking for is "Retrieve Source in Manifest From Org", which will retrieve any metadata declared by a package.xml. You start by creating a package.xml file (usually located in <project root>/manifest/package.xml) that lists the files you want to work on. You can see an example in this documentation.

https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/manifest_samples.htm

In my particular instance, I declared in the package.xml that I wanted all Apex classes, so I had the package.xml read as...
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>
    <version>47.0</version>
</Package>
```

Once you have a package.xml, you can retrieve the resources described by the package.xml by Right Clicking the Package.xml and select "Retrieve Source in Manifest From Org".

Basing this advice off of the command mentioned. You also commented on #1293 , which might give other readers looking for help more context. If this doesn't help clarify the issue, sorry about this. But thought spelling out the approach here might help everyone with this command, since it seems pretty common.

**Comment by lcampos** [comment]
@ybiyani have you gone through @dv297 's answer ? Can you confirm that's what you were running into ?

**Comment by ybiyani** [comment]
@dv297 @lcampos The problem is that I do not see "Retrieve Source in Manifest From Org" 
<img width="542" alt="Screen Shot 2020-01-08 at 8 11 14 PM" src="https://user-images.githubusercontent.com/8467517/72034754-25701c00-3253-11ea-92f8-44853cd97609.png">

**Comment by lcampos** [comment]
@ybiyani that's weird, I get those results in the screenshot if I right-click on the `manifest` folder but based on the image I'm assuming you are actually right-clicking on the `package.xml` file which should show that command (take a look at my screenshot below).
![Screen Shot 2020-01-09 at 10 41 42 AM](https://user-images.githubusercontent.com/1041842/72095108-b46d4a80-32cc-11ea-86d0-087d7ddf8f7d.png)

When you select the `package.xml` file do you see `ForceSourceManifest` on the bottom-right corner of your VSCode ?
![Screen Shot 2020-01-09 at 10 41 17 AM](https://user-images.githubusercontent.com/1041842/72095152-cbac3800-32cc-11ea-9ba6-7001aa2f9612.png)

I'm using version `47.10.0` of the Salesforce extensions and version `1.41.1` of VSCode.

**Comment by ybiyani** [comment]
@lcampos  I did not see "ForceSourceManifest"; it showed XML. 

However,after updating the file type association to ForceSourceManifest, the menu changed and I am now able to retrieve the source.   

Thx.

**Comment by lcampos** [comment]
@ybiyani glad it's working now, I'll close this issue now.
