### ISSUE TITLE
Support the TestVisible Annotation

### ISSUE THREAD

**Issue by dv297** [forcedotcom/salesforcedx-vscode#1835]
### Summary

The TestVisible annotation doesn't seem to be supported by the extension pack. Methods marked with the TestVisible annotation are not visible in tests.

### Steps To Reproduce:

1.  Create a private method
1. Mark the method with the `@TestVisible` annotation
1.  Create a test class
1. Write a test that attempts to use the method provided

### Expected result

The method should be visible and not show up in the "Problems" console.

### Actual result

The method is not visible and shows up in the "Problems" console.

### Additional information

Here is an example

<img width="1101" alt="Screen Shot 2019-12-09 at 9 27 45 PM" src="https://user-images.githubusercontent.com/5365325/70492664-c770dd00-1aca-11ea-8eab-c11fb839cc14.png">

<img width="1180" alt="Screen Shot 2019-12-09 at 9 10 52 PM" src="https://user-images.githubusercontent.com/5365325/70492307-9ba12780-1ac9-11ea-8e7b-8cd2202a77d9.png">

I've included a small repository that should reproduce the issue.
https://github.com/dv297/testvisible-reproduction

I'm still fairly new to Apex, so pardon me if I'm misunderstanding any of this. I believe the language server is compiled in apex-jorje-lsp.jar, so perhaps whatever repository holds the original source code to that jar would be the more appropriate place to log that, but I haven't really seen that code around.

**VS Code Version**: 1.40.2

**SFDX CLI Version**: 7.36.0-b1c4e9c7c8

**OS and version**: MacOS 10.14.6

**Comment by sc5148** [comment]
I don't understand why stuffs such basic and fundamental as these are not yet implemented.

**Comment by thebrettbarlow** [comment]
Please implement this. It should be baseline functionality.

I'm currently copying and pasting the method into the test class, but that could lead to human error. 

Let's say I do make a typo when pasting the method over. I'll probably ignore the warning I see on the method because I'll assume the warning is incorrectly saying `Method is not visible` when it's actually showing me a real warning.

**Comment by alan-morey** [comment]
Similarly, private inner classes annotated as `@TestVisible` also display a warning, with message like "Type is not visible: _\<class-name>_"

```apex
public class MyClass {
    @TestVisible
    private class InnerClass {
        public void doWork() {
            // do work
        }
    }
}

@IsTest
class MyClassTest {
    @IsTest
    static void testSomething() {
        MyClass.InnerClass inner = new MyClass.InnerClass(); // Problem reported on this line: "Type is not visible: MyClass.InnerClass"
        inner.doWork();
    }
}
```

**Comment by randi274** [comment]
WI created for this - W-7083578

**Comment by randi274** [comment]
Hey all! I'm now seeing that both issues have been fixed in the latest version of the extensions. 

1. TestVisible methods called from test classes are not reporting incorrect errors 
2. TestVisible inner classes called from test classes are not reporting incorrect errors 

![Screen Shot 2022-09-08 at 3 03 39 PM](https://user-images.githubusercontent.com/9795193/189205268-7507992f-a9f3-4c8c-8e32-4dcf0f9349db.png)

I'll go ahead and close this one for now. Let me know if anyone is seeing any residual issues here, and we can either reopen this issue, or create a new one.

**Comment by Triopticon** [comment]
This is still a very annoying issue and I have never seen it fixed. Please fix this so I dont have my problem window spammed with these not useful warnings. :-) 

<img width="2305" alt="Image" src="https://github.com/user-attachments/assets/85b3a802-88cd-4ecf-97a3-729f28023fb8" />

**Comment by ChrisDuncan-NIST** [comment]
@randi274 Please reopen this issue as it does not appear to be fixed.

Salesforce Extension Version in VS Code: Salesforce Extension Pack (Extended) v67.7.1
Salesforce CLI Version: @salesforce/cli/2.147.7 win32-x64 node-v26.7.0 (also tried with node-v22.23.1)
OS and version: Windows 11 Enterprise 25H2
VS Code version: 1.133.0
Most recent version of the extensions where this was working: No idea, this behavior has always been present for me.
