### ISSUE TITLE
"Push Source to Default Scratch Org" Command Palette command shows the --json flag but doesn't use it

### ISSUE THREAD

**Issue by jflowers45** [forcedotcom/salesforcedx-vscode#1838]
### Summary

When I use the Command Palette and choose "SFDX: Push Source to Default Scratch Org" it appears to be specifying that it's using --json, but the output is in the standard format.

### Steps To Reproduce:

1.  Make a change to any component.
1.  Open Command Palette and select "SFDX: Push Source to Default Scratch Org"
1.  Observe that it says `sfdx force:source:push --json --loglevel fatal` but the output is in the standard, non-JSON format

### Expected result

The output is formatted as JSON

### Actual result

The output is in line by line format

### Additional information

![image](https://user-images.githubusercontent.com/1021048/70574567-6866a300-1b72-11ea-8154-3960870620ac.png)

**VS Code Version**:
Version: 1.40.2

**SFDX CLI Version**:
sfdx-cli/7.33.2-045d48473e darwin-x64 node-v10.15.3

**OS and version**:
macOS Mojave 10.14.6

**Comment by brpowell** [comment]
Hi @jflowers45. So there's actually a trick going on here: We specify the --json flag because we want the results to be in an easily consumable format on the extensions side to show push errors through VS Code diagnostics (the "Problem" view). The downside to this is that we don't get the output of the command in an easy to read format in the output view. So after parsing the JSON and to support both views, the extensions take care of printing the table format to the output instead of the CLI.

**Comment by jflowers45** [comment]
@brpowell thanks for the explanation. Since this is the expected behavior I'm closing the issue.
