### ISSUE TITLE
Error "Please restart Code before reinstaling"

### ISSUE THREAD

**Issue by msrivastav13** [forcedotcom/salesforcedx-vscode#185]
### Summary
Trying to install the latest 41.4.0 version of SalesforceDX plugin and getting error to always restart the code

### Steps To Reproduce:
1. This is step 1.
Uninstall current version and try reinstalling the 41.4.0 version

### Expected result
_Describe what should have happened_.

Install DX 

### Actual result
Installation failed

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

Version 1.17.2 (1.17.2)

**SFDX CLI Version**:

sfdx-cli/6.0.9-3391781 (darwin-x64) node-v8.6.0

**OS and version**:

MAC OS 
![screen shot 2017-10-20 at 12 06 45 am](https://user-images.githubusercontent.com/2276156/31805002-8b8fe774-b52b-11e7-92e4-fba1e9e7c152.png)

**Comment by vazexqi** [comment]
I believe that this was an issue with Code itself. @msrivastav13 seems to have solved this by un-installing code. See https://twitter.com/msrivastav13/status/921390693960044544

However, there seems to an issue on VS Code https://github.com/Microsoft/vscode/issues/26828 that might be related.

I'm going to close this from our side first since this seems to be a VS Code-specific issue. We can reopen again if this is indeed an issue with our extensions.
