### ISSUE TITLE
Diff/Change Detection not Conflict Detection.  Very slow.  Run-time errors.

### ISSUE THREAD

**Issue by CarlParmenterCLDPartners** [forcedotcom/salesforcedx-vscode#2059]
I've been periodically retrieving with the beta feature turned on, without making any changes.  It thinks it's detecting conflicts, which is not correct.  I think it's just detecting changes made on server as diffs with what's local in the project.  Which is something, but not much.  

It's also very slow - it looks like it retrieves the package to a zip file, puts it in a temp local folder, unzips it and compares everything.  

It's also having Java errors - a non-existent temp scandir folder (on Windows).  

### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by smaddox-sf** [comment]
Hi @CarlParmenterCLDPartners - You are correct, currently it shows all files with differences.  If there are more files changed than you expected, you have a chance to investigate.  Otherwise, you can override and continue. 

Regarding performance, can you reply back with more info so we can look into it.  Please add:
**VS Code Version:
SFDX CLI Version:
OS and version:
Indication of project size (approx # of files):**

**Comment by smaddox-sf** [comment]
We've updated Conflict Detection beyond just checking diffs - check out the details in our doc - https://developer.salesforce.com/tools/vscode/en/user-guide/detect-conflicts
