### ISSUE TITLE
command 'sfdx.force.project.create' not found

### ISSUE THREAD

**Issue by xiang0731** [forcedotcom/salesforcedx-vscode#2081]
Hi there,
After update the windows from 1709 to 1803, I found it didn't show the "SFDX: Retrieve Source in Manifest from Org" when I right click in the manifest, and the ">SFDX: Create Project with Manifest" can't be used.

**VS Code Version**: Version: 1.43.0 (user setup)
**SFDX CLI Version**: sfdx-cli/7.36.0-b1c4e9c7c8 win32-x64 node-v10.15.3
**OS and version**: Win10 v1809

I can see the errors as below.
![image](https://user-images.githubusercontent.com/24264988/76979815-6f702f00-6973-11ea-9649-df3c0416b80f.png)

Thanks

**Comment by lcampos** [comment]
Hi @xiang0731 , thanks for opening this issue. It looks like your extensions are not activating properly because the Apex and CLI extensions are failing to activate. Unfortunately the screenshot you provided does not show why those two extensions are failing. Please provide an additional screenshot where we can see the errors on `salesforcedx-vscode-apex` and `salesforcedx-vscode-core` so we can understand what you're running into.

**Comment by xiang0731** [comment]
> Hi @xiang0731 , thanks for opening this issue. It looks like your extensions are not activating properly because the Apex and CLI extensions are failing to activate. Unfortunately the screenshot you provided does not show why those two extensions are failing. Please provide an additional screenshot where we can see the errors on `salesforcedx-vscode-apex` and `salesforcedx-vscode-core` so we can understand what you're running into.

Thank you very much for your reply. 
These days I'm trying to reinstall the JDK, and the last time I opened the VS code, it reinstalled the extension, and the command worked. 
Maybe the windows update made the JDK unworked? I will keep investigating the root cause on it.
Thanks again.
