### ISSUE TITLE
Is there a way to connect to a trailhead org?

### ISSUE THREAD

**Issue by HazardDev** [forcedotcom/salesforcedx-vscode#214]
### Summary
I'd just like to know if there is a way to authenticate with a trailhead org and learn about it as we learn about the platform.

### Steps To Reproduce:
1. Try to auth with trailhead

### Expected result
Login with org id or using `-r trailhead-url.lightning.salesforce.com`

### Actual result
No org with that ID

**VS Code Version**: 1.18

**SFDX CLI Version**: 6.0.14-2af879b

**OS and version**: Windows 10 Enterprise, 64 Bit

**Comment by guw** [comment]
Disclaimer: I'm not a 100% sure what a _"trailhead org"_ is. I suspect you mean something like a Trailhead Playground mentioned [here](https://trailhead.salesforce.com/en/projects/trailhead_on_mars/steps/trailhead_on_mars_step_1)? Can you clarify how you created the org?

I don't believe those orgs have DevHub enabled for creating scratch orgs. In order to use the extension in VS Code you need to be working within a Salesforce DX project, i.e. a `sfdx-project.json` file must be present in the folder/workspace opened in VS Code. Additionally, you need to authenticate with a Salesforce DX enabled Dev Hub in order to create scratch orgs.

Please have a look at the [Salesforce DX Setup Guide](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_intro.htm). Section [Enable the Dev Hub in Your Org](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_enable_devhub.htm) explains how to enable it in your org and also lists the orgs it can be enabled it. It's also possible to [sign-up for a trial org](https://developer.salesforce.com/promotions/orgs/dx-signup).

**Comment by guw** [comment]
@HazardDev It's possible to use the CLI with a Trailhead Playground org. The trick is to set a password. There are instructions for [setting a password for such an org](https://force.desk.com/customer/portal/articles/2659738-how-to-get-a-password-for-my-trailhead-playground?b_id=13478). Once you have a password you can use `force:auth:web:login` to authenticate with such an org.

**Comment by HazardDev** [comment]
Thanks. I’m thinking that’s exactly what I need.
