### ISSUE TITLE
Add Token Refresh Method to salesforcedx-vscode

### ISSUE THREAD

**Issue by JosephAllen** [forcedotcom/salesforcedx-vscode#2142]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Export the `@salesforce\core` authInfo.RefreshFn method in `salesforcedx-vscode-core`. This would improve performance for dependent extensions and allow bypassing the CLI to execute commands.

**Describe alternatives you've considered**
It appears that the `salesforcedx-vscode-core` does not monitor updates to the usersauthInfo files so tokens can get out of date. 

**Additional context**
Lazy Load of tokens into environment fields for later use will speed up performance significantly. See [Apex Code Runner](https://github.com/JosephAllen/apex-code-runner) as a proof of concept.

**Comment by lcampos** [comment]
Hi @JosephAllen , can you clarify if you what you are looking for is for the token refresh being handled by the `salesforcedx-vscode-core` extension or for `salesforcedx-vscode-core` to expose an api for a dependent extension to refresh the token ? I ask this because if you want to avoid running a CLI command then you wouldn't depend on `salesforcedx-vscode-core` and could just use the [@salesforcedx/core](https://www.npmjs.com/package/@salesforce/core) module directly.

**Comment by JosephAllen** [comment]
@lcampos,an early version of the apex code runner used the [@salesforcedx/core](https://www.npmjs.com/package/@salesforce/core) It made the vsix way to big (~6mb). By using an extension dependency to the `salesforcedx-vscode-core` extension I cut the size down to ~40kb.

Here is an example: [extensionDependencies](https://github.com/JosephAllen/apex-code-runner/blob/80effe404aa8d472ba4027c343802c1a9be6a404/package.json#L236) and the actual implementation: https://github.com/JosephAllen/apex-code-runner/blob/80effe404aa8d472ba4027c343802c1a9be6a404/src/services/authenticate.ts#L5

Does this help, or did I answer a question you did not ask :-)

Also Githbub was giving the stick eye because the `@salesforcedx/core` has a dependency with security issues.

**Comment by lcampos** [comment]
Thanks, that makes sense. We're working on making `@salesforce/core` smaller and the reason why I suggest its use is because that's what we use internally on `salesforcedx-vscode-core`. Other than that, I'm not sure `salesforcedx-vscode-core` should provide an api to refresh tokens since the patterns vscode allows for this to happen do not provide a reliable contract for other extensions, outside of our control, to consume. By that I mean that if we decide to change that api there's not a good way to test it doesn't break dependent extensions unless you run that other extension.

Specific to the security issue, is it any of the ones already surfaced as an issue in that repo ?

**Comment by JosephAllen** [comment]
The `@salesforce/core` module has a dependency to a specific version of `mkdirp` version `0.5.1` which has a known vulnerability. (mkdirp@0.5.1 vulnerabilities)[https://snyk.io/test/npm/mkdirp/0.5.1].

>Affected versions of this package are vulnerable to Prototype Pollution. The library could be tricked into adding or modifying properties of Object.prototype using a constructor or __proto__ payload.
