### ISSUE TITLE
macOS Extension Pack not showing SFDX commands in command palette

### ISSUE THREAD

**Issue by rdclk23** [forcedotcom/salesforcedx-vscode#2249]
Salesforce CLI works fine thru VS Code terminal window but I cannot get any sfdx commands to appear in Command Palette (cmd+shift+P), says 'No commands matching' .  The Salesforce extension pack is installed but does not seem to be working.  

VS Code version 1.42.1
Salesforce Extension Pack 48.2.0
MacOs Catalina 10.15.3
Salesforce CLI 7.36.0 darwmin-x64 node-v10.15.3

:

**Comment by gmpmovies** [comment]
I occasionally have this same issue, I've always assumed that it was because VS Code was not recognizing it as a SFDX project. Closing and restarting VS Code has almost always resolved the issue for me. Occasionally I've had to run `sfdx force:auth:logout --all` and then reauthorize the org I'm using in order to see certain commands like `push source to default scratch org` which occasionally disappear.

**Comment by lcampos** [comment]
Hi @rdclk23 do you see any error when opening VSCode's Dev Console (Help > Toggle Dev Tools and then selecting Console) ?

Normally what it takes to see all the SFDX commands is for you to open a project with a valid sfdx-project.json file at the top level.
