### ISSUE TITLE
Org auth throws REST API not enabled error

### ISSUE THREAD

**Issue by mjmaurya** [forcedotcom/salesforcedx-vscode#2387]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `49.3.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.47.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
![Screenshot (277)](https://user-images.githubusercontent.com/45433443/89037548-53868c00-d35c-11ea-9730-3c4b4e9c3aba.png)
![Screenshot (278)](https://user-images.githubusercontent.com/45433443/89037557-55e8e600-d35c-11ea-80c0-9d246e3875b1.png)

**Comment by lcampos** [comment]
Thanks for opening this issue @mjmaurya . Looking at the error thrown (`The REST API is not enabled for this organization`) by the `force:auth:web:login` command seems the issue is related to your user not having the correct API access needed. Can you confirm the user you are authenticating with does have api access ?
