### ISSUE TITLE
TypeError: Cannot read property 'getInstance' of undefined

### ISSUE THREAD

**Issue by dhaniksahni** [forcedotcom/salesforcedx-vscode#2419]
Getting **TypeError: Cannot read property 'getInstance' of undefined**  error while deploying code to the org.

**Comment by smaddox-sf** [comment]
Hi @dhaniksahni - Thanks for submitting this.  Can you add the details of the issue you experienced along with the steps to replicate?  From the information logged, I can't tell what the problem is.  Please also include the following:

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

Lastly, can you verify if the CLI configuration is [setup as described here](https://developer.salesforce.com/tools/vscode/en/troubleshooting/#set-salesforce-cli-path-windows)?

**Comment by lcampos** [comment]
Hi @dhaniksahni , this is a duplicate from CLI issue [#564](https://github.com/forcedotcom/cli/issues/564). Please follow that issue for more information.
