### ISSUE TITLE
Variable does not exist: Schema.SObjectType.Case

### ISSUE THREAD

**Issue by jarodwsams** [forcedotcom/salesforcedx-vscode#2665]
### Summary

Any time I have references to `Schema.SObjectType.SObject.method()`, where SObject is the API name of any object in the environment, VS Code reports the following problem:
```Variable does not exist: Schema.SObjectType.SObject```

One example is when trying to retrieve RecordTypeId by Name using `Schema.SObjectType.SObject.getRecordTypeInfosByName()`
![image](https://user-images.githubusercontent.com/22972834/97050955-e68e2700-1543-11eb-82ec-2071694e9a43.png)

### Steps To Reproduce:

1.  Make any functioning reference to `Schema.SObjectType.SObject`, where `SObject` is the API name of an object
1.  Deploy the code to the environment
1. Note a successful deployment
1. Note the Problem panel and the problem `Schema.SObjectType.SObjectType`

### Expected result

This should not be reported as a problem.

### Actual result

The reference to `Schema.SObjectType.SObject` is reported as a problem.
![image](https://user-images.githubusercontent.com/22972834/97050914-d413ed80-1543-11eb-8224-188596120af6.png)

### Additional information

**VS Code Version**: 1.50.1
**SFDX CLI Version**: sfdx-cli/7.74.1-32db2396ed win32-x64 node-v12.18.3
**OS and version**: Windows 10 Enterprise, Version 1803

**Comment by lcampos** [comment]
Thanks for logging this @jarodwsams . Can you confirm if you have enabled the setting `salesforcedx-vscode-apex.enable-semantic-errors` ? I can't replicate this behavior without enabling that.

**Comment by jarodwsams** [comment]
Indeed, I have.
________________________________

**Comment by attilah** [comment]
If I have `Account.SObjectType` in the code with the aforementioned setting disabled it does not have yellow squiggles, but also it does not have any tip on hovering and will not bring up and other code information after hitting `.`

If I go to definition on `Account` I can see that it does not have the `SObjectType` member obviously as it is coming from somewhere else.

**Comment by smaddox-sf** [comment]
Thanks for confirming @jarodwsams .  The semantic errors are bugging and I'm linking this one back to #1331.

@attilah - It sounds like you are missing code smartness.  Perhaps because you haven't refreshed SObject definitions or maybe java is missing?  Here's a couple resources that can help.  Please log a new issue with details if you still have trouble.  We seek to keep one discussion per issue so we can keep everything straight.

[Code smartness](https://developer.salesforce.com/tools/vscode/en/apex/writing/#code-smartness-for-sobjects)
[Java setup](https://developer.salesforce.com/tools/vscode/en/getting-started/java-setup)
