### ISSUE TITLE
Exclude Expired Scratch Orgs from Any Command

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/salesforcedx-vscode#2751]
**Is your feature request related to a problem? Please describe.**
No, it is to prevent problems and unnecessary list commands just to check if the org is or not expired after trying to push to a expired scratch org.

**Describe the solution you'd like**
SFDX knows when the SO is expired, so the VSCode Extension can use it to never show any commands available for Scratch Orgs when they are expired. This way users don't waste time selecting a SO which is expired. For instance, I was able to set the Default Scratch org, using the extension button, to an Expired Scratch Org.

![image](https://user-images.githubusercontent.com/55927613/99661896-6a143880-2a5c-11eb-994d-e1a243e262ca.png)

**Comment by lcampos** [comment]
This is a good idea but I think we might have to limit it to showing a message when activating the extension since disabling the commands might not provide enough information to the user on what is going on.

When you talk about selecting an expired scratch org, where you using the Org Picker ? A few releases ago (release 49.10.0) we merged a PR that indicates when the scratch org is expired.

<img width="1361" alt="org_picker_expired_orgs" src="https://user-images.githubusercontent.com/1041842/101561745-b62b0c80-397a-11eb-8638-3f622ed2bd96.png">

**Comment by AllanOricil** [comment]
Yes, I'm using that button and I can see these red X on expired orgs. But the problem is that I can still select an expired org. I think it is better if you just remove the expired ones. Or is there a reason for allowing users to select them?

**Comment by lcampos** [comment]
@AllanOricil I forgot to reply to this. The reason we keep those orgs around is because a significant part of our user base are new to Salesforce development or new to using scratch orgs, etc. If we start removing orgs in the background this will make their experience of using the extensions confusing/bad. This is why I prefer explicitly showing a message and having the user click a button so expired orgs get removed.

**Comment by AllanOricil** [comment]
> @AllanOricil I forgot to reply to this. The reason we keep those orgs around is because a significant part of our user base are new to Salesforce development or new to using scratch orgs, etc. If we start removing orgs in the background this will make their experience of using the extensions confusing/bad. This is why I prefer explicitly showing a message and having the user click a button so expired orgs get removed.

@lcampos  But the issue I wanted to report here was different. Like, I don't see a reason for showing expired scratch orgs on the list of available scratch orgs when clicking on the "select default scratch org button".

And now, after your response I thought about something that would be very nice to have. What if you add an optional config attribute to automatically exclude expired scratch orgs when it is true? Then me and all other developers that constantly work with scratch orgs would not need to keep excluding one by one. We also wouldn't waste time running "sfdx force:org:list --all" to get the list of expired scratch orgs just to delete them after. This is also good when we work on a company that has multiple teams working on the same devhub with limited number of SO that can be created. Very often we see developers forgetting to exclude their expired scratch orgs and this counts against the limit. Then another issue is that our deployment Pipelines get stuck because it can't create a SO. But if we configure everyone's sfdx to automatically delete the expired scratch orgs, I'm sure this problem will happen less frequently. I'm sure this would be a really good feature.

**Comment by lcampos** [comment]
@AllanOricil I like that approach better, having it behind a vscode setting would work for everyone. 

cc @smaddox-sf

**Comment by AllanOricil** [comment]
> @AllanOricil I like that approach better, having it behind a vscode setting would work for everyone.
> 
> cc @smaddox-sf

@smaddox-sf and @lcampos would you guys have a position to work remotely in your team? I have some ideas that I would like to share and see it implemented

**Comment by lcampos** [comment]
hi @AllanOricil , we unfortunately don't have any open positions in the team at the moment. Whenever this changes we'll make sure to post about it in the repo.
We are still open to meet and talk about your ideas and see how they map to our roadmap. Let us know and we can set something up.
