### ISSUE TITLE
Some SFDX commands from Command Palette shows "Salesforce CLI not installed", running the same command in terminal works. [MAC]

### ISSUE THREAD

**Issue by jehicks2** [forcedotcom/salesforcedx-vscode#2773]
### Summary

Running some commands from the Command Palette shortcut results in 'Salesforce CLI not Installed' in Output. However, the CLI is installed and shows correct output when typing 'sfdx' in VS Code command terminal. This is on a Mac.

<img width="925" alt="Image of command sfdx working in official VS Code terminal" src="https://user-images.githubusercontent.com/10644304/100782091-265cef80-33c9-11eb-83b5-dd80943c7c7f.png">

### Steps To Reproduce:

1.  In an SFDX Project, attempt to authenticate with 'SFDX: Authorize an Org' from the VS Code command palette. 
2. Select Standard
3. Default or any Alias (doesn't matter, this is subjective) 

### Expected result

The command is suppose to run and open default browser to log in. (Default browser is set as Chrome)

### Actual result

SFDX fails to run. Output of 'Salesforce CLI is not installed' 

<img width="925" alt="Screen Shot 2020-11-23 at 1 54 12 PM" src="https://user-images.githubusercontent.com/10644304/100782131-32e14800-33c9-11eb-98be-979a720251bf.png">

### Additional information: 
This is related (I think) to this issue #2654 
I installed the Salesforce CLI through the [online download](https://developer.salesforce.com/tools/sfdxcli). 

**VS Code Information **:
Version: 1.51.1

**SFDX CLI Version**:
sfdx-cli/7.81.0-7b953c80d1 darwin-x64 node-v12.18.3

**Salesforce CLI Integration Extentions**:
50.5.0

**OS and version**:
MacBook Pro (16-in, 2019)
OS: macOS Catalina
Version: 10.15.7

**Comment by lcampos** [comment]
I haven't been able to replicate this issue yet. @jehicks2 is there any particular setup step you ran ? e.g. some custom shell configs

**Comment by klouf-mp** [comment]
I have also been experiencing this for several months now. Reloading the VSCode window resolves the issue for me (from the Command Palette "Developer: Reload Window").

Additional thoughts:
* This usually only occurs after a fresh launch of VSCode, not when opening new windows/projects if VSCode is already open. It has occurred randomly on already open projects, but extremely rarely (maybe less than a handful of times).
* I almost always have several VSCode windows open at all times (all large SFDX projects) and have VSCode configured to relaunch open windows/documents on launch so it takes a couple minutes for everything to open and initialize when I do a fresh launch.
* I also have been getting an error from VSCode more recently when launching the app: "Unable to resolve your shell environment in a reasonable time. Please review your shell configuration." More information on that here: https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-is-slow-error-warning

The two seem to me like they are related and that it's just taking too long for VSCode to launch and initialize all of the extensions (so much for having a mid-range 2017 MB Pro I guess 🤷‍♂️ ), but that's just a guess.

All in all since reloading the window resolves the issue and I'm not launching VSCode from naught that often it's not really too much of a pain for me personally, but figured i'd chime in if I could provide any additional info that might help.

**Comment by costonb** [comment]
I've also been seeing this as well as others on my team.  Restarting VSCode seems to fix it.  We also have fairly large projects and I have several projects open at once in different windows.  I typically just leave VSCode open constantly unless the issue happens, then I restart it.  I have not noticed the Unable to resolve your shell environment in a reasonable time error that @klouf-mp is seeing though.  Also for me it is not on a  fresh launch  of VSCode, as that is generally how I fix the issue.  It  happens for me when  VSCode has been running for a while, like after a day or two.
