### ISSUE TITLE
Open Source the Apex Language Server

### ISSUE THREAD

**Issue by ChuckJonas** [forcedotcom/salesforcedx-vscode#305]
The language server is currently only added to this project as a compiled jar.  Please release the source so we can contribute to that functionality.  Many things are broken

**Comment by vazexqi** [comment]
@ChuckJonas - Thanks for trying this out. Could you file bugs/provide details for things that are broken? Some things like Go To Definition/ Find All References are implemented in phases so some parts are not working yet. There are also limitations around the parser (it's not a full incremental parser so certain errors confuse it). But, again, bugs with repro steps would help us work on fixing things :-)

CC: @ntotten on open sourcing the language server portion.

**Comment by Xixiao007** [comment]
@ntotten my 5 cent,

Talking to language server is an intriguing point for people, like me, to contribute to VSC salesforce plugin.
Auto formatting Apex, for example, is one of tasks I want to contribute to in spite of limited spare time.

I really wish the prerequisites can be set in place so that other regular developers working in Salesforce industry have the chance to contribute back to tools they use daily.
  
Regardless, thanks for the great vsc plugins, DX, language server implementations, etc. Your guys have done great work. Looking forward.

**Comment by ntotten** [comment]
To clarify, I completely understand the desire to have this open sourced. We regularly talk with the partners you mentioned and are working to make their jobs easier. The main reason I was asking "why" was to help build the case - the more real customer data we have the more it helps us justify the time it would take to make this happen. While I wish this was just as simple as pushing the source to github, it is unfortunately not. Right now the LSP is tied into the compiler of Apex, which is in turn tied into a number of other internal libraries. We would need to go and split these apart, publish some non-open source libraries to maven, etc. in order to make the open source LSP usable. This is will take time from other projects on the dev tools team so we need to find the right balance. The feedback in this thread along with all the conversations we have with Scott and others are critical in helping us prioritize.

I'd love to chat more about this and what else we can do to help out. If you want you can email me directly, ntotten@salesforce.com or book some time for us to chat: https://calendly.com/totten/office-hours

**Comment by asknet** [comment]
Is the bundled jar, anyway useful to use standalone and hence can be integrated with other IDE's?

**Comment by ChuckJonas** [comment]
@asknet in theory you could call the jar as long as your system has java runtime... However, last I checked it's not well documented (although should more or less follow standard LSP)

**Comment by ntotten** [comment]
I have shared this feedback internally. As it is not directly related to VSCode im going to close this issue.

**Comment by jonathanwiesel** [comment]
Although this has been closed for quite some time, #2554 is an example of a feature that the open source community could give a hand on

**Comment by gabrielcowley** [comment]
I'm aware this issue has been closed for a long time, but I'd like to add my voice to this request and give details about my use case.

Rather than integrating the Apex Language Server with an IDE, I want to be able to collect semantic information about Apex files in a given project - specifically, information about dependencies/references to other Apex files and metadata components of different types. I don't know of any open source tools that can provide this kind of semantic analysis on Apex code.

This can be achieved by executing the JAR file, but this is not viable for my team because of security concerns. The advantage of open sourcing the ALS for us would be that we could scan the ALS source code for vulnerabilities in dependent open source code. I don't believe this can be done with a compiled JAR executable - if it or its dependencies contain vulnerabilities, we don't have a reliable way of detecting and dealing with this.
