### ISSUE TITLE
Authorisation required each day

### ISSUE THREAD

**Issue by gonardfreeman** [forcedotcom/salesforcedx-vscode#3070]
### Summary

Each day I need to set default org and authorise it.

### Steps To Reproduce:

1.  Authorise an dev org.
2.  Leave VSCode as is (do not close)
3. Comeback day after
4. Try deploying

### Expected result

Your metadata successfully deployed 

### Actual result

`Error: INVALID_SESSION_ID: Session expired or invalid`

### Additional information

![Screenshot 2021-03-17 at 09 14 06](https://user-images.githubusercontent.com/16113714/111429086-25926400-8701-11eb-965b-8e4c0de80dbb.png)

If I trying to make deploy via command line it works perfectly, so I assume this an issue with extension itself

I understand that it is not enough info. I could try to go to VS Code console and get some debug from it next time it occure.

**VS Code Version**:

`Version: 1.54.3`

**SFDX CLI Version**:

`sfdx-cli/7.90.2 darwin-x64 node-v14.16.0`

**OS and version**:

macOS Big Sur

Version: 11.2.3 (20D91)

**Comment by gonardfreeman** [comment]
Little update:

![Screenshot 2021-03-17 at 09 18 45](https://user-images.githubusercontent.com/16113714/111429568-d1d44a80-8701-11eb-9d6c-63481e1d247a.png)

I think some part of your extension is deleting default username?

**Comment by lcampos** [comment]
Hi @gonardfreeman, I don't think any deletion is happening, at least by the Salesforce extensions. Based on the screenshot of the errors you've shared above I think what is happening is that you've created your project directly under your user file path ( `/Users/dimabondarenko/<project_name>`) which is the same location where the CLI stores the global configurations ( `/Users/dimabondarenko/.sfdx`). This would cause the Salesforce extensions to have that behavior you are seeing since they are also expecting an `.sfdx` directory which is used to set the project configurations.

If this is your configuration, move your project to a different file path e.g. `/Users/<username>/Documents/<project_name>/` and that should clear the issues you are running into.

**Comment by gonardfreeman** [comment]
@lcampos no it isn't in same folder. But it in `.nosync` folder (if you don't want to sync folders with iCloud you should add to name such prefix). Mb that became a case, because previously it wasn't an issue. But I'll try to move it to dev folder today and let you know tomorrow if it helps.
Thanks.

**Comment by gonardfreeman** [comment]
GM @lcampos !
No, it wont help. after I've moved it the issue is still reproducible.

![Screenshot 2021-03-19 at 08 36 34](https://user-images.githubusercontent.com/16113714/111741239-cfebc200-888e-11eb-89eb-d314e3654c2d.png)


https://user-images.githubusercontent.com/16113714/111741827-cca50600-888f-11eb-84fe-8ee1375f3bc8.mov


https://user-images.githubusercontent.com/16113714/111741837-d2025080-888f-11eb-8d48-f7612b94401c.mov

**Comment by gonardfreeman** [comment]
No update didn't helped 😞

**Comment by gonardfreeman** [comment]
@lcampos any news?

**Comment by smaddox-sf** [comment]
Hi @gonardfreeman - Did the need to authorize each day happen within the last month or so?  If so, we have a known issue on the CLI at the moment where the REST API is not auto-refreshing your auth token.  That issue will soon be fixed but in the meantime, [there is a workaround that is explained here](https://github.com/forcedotcom/cli/issues/942).

**Comment by gonardfreeman** [comment]
Yep. Thanks a lot!
