### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Kodiackk** [forcedotcom/salesforcedx-vscode#3073]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-lwc`
- Extension Version: `51.4.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Kodiack\AppData\Local\Temp\salesforce.salesforcedx-vscode-lwc-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
In order to diagnose this issue, we need more information.  Next time you hit this issue, please copy the info from the clipboard.  Alternatively, you can also [open a new issue using the 'bug' template](https://github.com/forcedotcom/salesforcedx-vscode/issues/new?assignees=&labels=&template=Bug_report.md) anytime with more details. Closing this one as it's not actionable.
