### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by rajeshnagandla** [forcedotcom/salesforcedx-vscode#3078]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `51.5.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.54.3`
![image](https://user-images.githubusercontent.com/28894550/111731559-1b2fb180-884a-11eb-8d2b-a08db82a798e.png)

**Comment by smaddox-sf** [comment]
In order to diagnose this issue, we need more information.  Next time you hit this issue, please copy the info from the clipboard.  Alternatively, you can also [open a new issue using the 'bug' template](https://github.com/forcedotcom/salesforcedx-vscode/issues/new?assignees=&labels=&template=Bug_report.md) anytime.
