### ISSUE TITLE
Unknown Exception when retrieve package.xml

### ISSUE THREAD

**Issue by filipaGitHub** [forcedotcom/salesforcedx-vscode#3188]
Hi,

I am trying to retrieve source from my org through the **package.xml** - **SFDX:Retrieve This Source from Org**
I am getting this error:

**SFDX: Retrieve Source from Org failed to run**
**Unknown Exception**

I have been working on this project in GitHub and it was working just fine until it suddently stopped retrieving throught the **package.xml**
I have already tried to reinstall Salesforce Extension Pack from Visual Studio Code. (Complete Package which comprises of multiple extension) from visual studio and also visual studio itself but I am still getting this error.

If I use the command line **sfdx force:source:retrieve -x manifest/package.xml** it works. But it only works if I use the command line and before I didn't have to use it.

<img width="960" alt="retrieve" src="https://user-images.githubusercontent.com/78536080/116584575-67711580-a90f-11eb-9abe-a26ef1615336.PNG">
<img width="750" alt="failed" src="https://user-images.githubusercontent.com/78536080/116585441-51b02000-a910-11eb-87e3-2576970e06d6.PNG">

**Comment by brpowell** [comment]
Thanks for filing @filipaGitHub. We have a fix going out this week that will surface a better error message when running deploy/retrieve operations. I'm going to close this as a duplicate since this issue is filed here #3137. In the meantime feel free to turn off the new deploy/retrieve flag in your settings (more details [here](https://developer.salesforce.com/tools/vscode/en/user-guide/perf-enhancements/#setup)). Once the release goes out feel free to turn it back on if you'd like to see a hopefully more actionable error message and continue to have performance benefits with the new experience. Thank you for your patience.
