### ISSUE TITLE
Empty Differences - File Diff incorrectly identifies file differences after deploy/retrieve

### ISSUE THREAD

**Issue by rchundu-lyft** [forcedotcom/salesforcedx-vscode#3245]
For last few months, I have been getting empty differences with files between my org and vs code when there are no differences. No matter what I do (I committed the files, but still same issue), I keep getting these differences in 100s files.

![image](https://user-images.githubusercontent.com/65677387/118692833-16e32e80-b7d0-11eb-8996-7f6888996a4c.png)

![image](https://user-images.githubusercontent.com/65677387/118692869-206c9680-b7d0-11eb-9435-1ebdfb327c9f.png)

![image](https://user-images.githubusercontent.com/65677387/118692912-2b272b80-b7d0-11eb-9f7d-d8f60ed039c6.png)

**Comment by rchundu-lyft** [comment]
Submitting this in CLI Github.

**Comment by AnanyaJha** [comment]
Thanks for reporting this @rchundu-lyft, this is an issue identified in the Extensions experience. We've been able to repro it and we've logged a bug to address it. Internal WI #W-9296060

**Comment by rchundu-lyft** [comment]
Thanks @AnanyaJha. I thought it was an issue with CLI, not with VS Code extension. But glad you were able to reproduce it in VS Code.

**Comment by xyc** [comment]
@rchundu-lyft Just to confirm: Do you see the issue from running "SFDX: Diff File Against Org"? Do you still see it with "Experimental: Deploy Retrieve" setting toggled on?

- For sharing rules, it appears that there's a single newline at the end of file when deployed. You can configure the default XML formatter to format the file on saving so that it would enforce one newline.
- For LWC `js-meta.xml`: we cannot reproduce it on our end.

If you have seen empty diffs in Apex files, please let us know too.

**Comment by rchundu-lyft** [comment]
@xyc I am not noticing this issue anymore and can be closed.
