### ISSUE TITLE
Detect Conflict at sync feature is not working

### ISSUE THREAD

**Issue by puchini104** [forcedotcom/salesforcedx-vscode#3414]
### Summary
I was using without problems the funtionality of "Detect Conflict at sync" till last week, but from now on each time that I retrieve something it does not work. 

### Steps To Reproduce:
This is step 1. File->Preferences->Setting Extension-> Salesforce Feature Preview
This is step 2. Check the checkbox Detect conflict at sync.
This is step 3. Retrieve from package.xml

### Expected result
It should not retrieve without showing conflict first

### Actual result
Retrieve all components

### Additional information

Version: 1.58.0 (system setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:55.083Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by smaddox-sf** [comment]
Hi @puchini104 - Thanks for reaching out on this.  We have work in flight to deliver the remainder of Conflict Detection.  With the beta last year, the Conflict Detection was purely doing a diff and showing you anything with a difference.  This led to a lot of noise since there will be diffs every time you deploy (assuming you made changes).  With the updates to this feature, we are upgrading the logic to compare the modified date in the org with the local sync date to surface potential conflicts on deploy.  This logic doesn't quite make sense for retrieves and can lead to unexpected overwrites, so we will no longer be checking for potential conflicts for retrieves.  Instead, you can [execute a diff](https://developer.salesforce.com/tools/vscode/en/user-guide/source-diff), which now works for directories and additional metadata types.  

Our updated documentation will be published for Conflict Detection later this week.  In the meantime, [you can see the original spec here](https://github.com/forcedotcom/salesforcedx-vscode/issues/2034).

**Comment by ralphcallaway** [comment]
still useless, every save generates a conflict regardless of whether there is one

**Comment by smaddox-sf** [comment]
@ralphcallaway - Have you checked out the latest version of conflict detection?   With the updates to this feature, the logic now compares the modified date in the org with the local sync date to surface potential conflicts on deploy.  You should not be seeing a conflict every time you deploy (unless there have been changes in the org).  [You can see more details in the documentation](https://developer.salesforce.com/tools/vscode/en/user-guide/detect-conflicts).  If you are seeing conflicts on deploys when there haven't been changes in the org, please consider [opening a new issue with the repro details](https://github.com/forcedotcom/salesforcedx-vscode/issues/new?assignees=&labels=&template=Bug_report.md&title=) so we can get to the bottom of it.
