### ISSUE TITLE
Improve Apex syntax highlighting (braces, accolades...)

### ISSUE THREAD

**Issue by mcartoixa** [forcedotcom/salesforcedx-vscode#342]
### Summary
Syntax highlighting in Apex does not seem to distinguish properly braces, accolades and other delimiters (block for instance). This makes the source code very monochromatic and hard to read.

### Steps To Reproduce:
1. Open an Apex class

### Expected result
The syntax highlighter should be able to recognize and properly categorize delimiters, like so many other languages do, with categories like _meta.block_, _meta.brace_, _meta.tag_, _punctuation_ (or even better _punctuation.section.array.begin_)...

### Actual result
 Almost every character in a method is categorized as _source.apex_ ou _meta.method.apex_, making the source code monochromatic and hard to read.

### Additional information

Alomost every character has the same color in the screenshot below (even the regular expression is not recognized):
![image](https://user-images.githubusercontent.com/1251985/37336251-20fa76b6-26b1-11e8-89c3-5e6bcd33520b.png)

**VS Code Version**:
1.21.0

**Comment by vazexqi** [comment]
@mcartoixa - Thanks for reporting this. We are aware of the current limitations and are planning to address parts of them. The syntax highlighter that we are using (https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode-apex/syntaxes/apex.tmLanguage) is based on some old TextMate grammar (it's a modified copy of https://github.com/superfell/ApexMate/blob/master/plugin/Syntaxes/Apex.tmLanguage).

@ntotten - Per our discussion yesterday.

**Comment by vazexqi** [comment]
Tracked internally as W-4800460

**Comment by lcampos** [comment]
Hi @mcartoixa, I'm working on fixing the tokenization issues you mentioned, I'm running some tests and would like to test with the code you used. Could you share a code sample so I can test against it?

**Comment by lcampos** [comment]
Thanks for the quick response @mcartoixa , I'm attaching a comparison (using your code sample) between the new language grammar rules (left) and the ones we currently ship with (right). I'm using 'Dark +' theme on the screenshots but similar results can be seen with any theme since the new tokens follow TextMate's guidelines. This are the first set of language grammar changes we'll be shipping since we feel they already provide a better experience. They will be part of this week's v42.16.0 release (May 17th). 

Thanks for your feedback and let us know what you think once you try out the changes.
![new-old-titles](https://user-images.githubusercontent.com/1041842/40083754-06edcf8c-584a-11e8-8916-d06fec57e5df.png)
![close-curlybrace](https://user-images.githubusercontent.com/1041842/40083773-0d1ee670-584a-11e8-8c8e-2997a5e6b79a.png)

**Comment by vazexqi** [comment]
We are closing this as part of https://github.com/forcedotcom/salesforcedx-vscode/pull/415

@mcartoixa - If you see any other issues, please open a new issue for this. Thanks again for reporting this.
