### ISSUE TITLE
Version for Visual Studio (2015+)?

### ISSUE THREAD

**Issue by cemerson** [forcedotcom/salesforcedx-vscode#349]
Sorry if there's more appropriate place to ask this but is there a version of this for standard "Visual Studio" users and not just "Visual Studio Code" users? If not, is there a way to force the "Visual Studio Code" version of this into "Visual Studio"?

**Comment by vazexqi** [comment]
@cemerson - Thanks for asking about this. This only works for Visual Studio **Code** since that runs natively out of the box for all major OS – Linux, Mac, and Windows. 

Per my understanding, Visual Studio is still primarily a Windows-based product. There are "Visual Studio for Mac" and some version of Xamarin for Linux, but there is no unifying SDK to develop for all three Visual Studio platforms.

So there are no plans to support Visual Studio itself at this time. I'm going to close this for now.

**Comment by cemerson** [comment]
Thank you, sir. It is starting to look like Visual Studio Pro (not VS Code) has few to no (real) options for working on SFDC Apex code (outside some flimsy, 3rd party/indie solutions). I'd use SublimeText and MavensMate but the latter has stopped development and I can't get Sublime working easy/nice with TFS. Anyhow... the quest continues! 

Thanks again for confirming this though.

**Comment by troveryor** [comment]
@cemerson Been a while since I used full Visual Studio but can't you install VSCode and use that anyway for Apex work? 

It should give you the TFS integration you are looking for with the Microsoft supplied extension: https://marketplace.visualstudio.com/items?itemName=ms-vsts.team
