### ISSUE TITLE
Unable to install force-ide tool ("force-ide-Beta-win32.win32.x86_64") for salesforceDX-VScode. It throws error related to.. \workspace\.metadata\.log.  file

### ISSUE THREAD

**Issue by sumitkr49** [forcedotcom/salesforcedx-vscode#360]
unable to install force-ide tool ("force-ide-Beta-win32.win32.x86_64") for salesforceDX-VScode
i downloaded zip file for salesforcedx-vscode and tried to install it after unzipping it. unable to do that .. it throws error saying.. an error has occurred see the log file 

### Steps To Reproduce:
1.downloaded file from below link
" https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode "
2. click on forceide application or .exe file to install it.

### Expected result
FORCE-IDE tool should have installed on my system to work on sfdx

### Actual result
Geeting an ERROR which says -- An error has occurred , see the log file
C:Users\mycomputername\Application Data\SalesforceIDE\workspace\.metadata\.log.

and i tried to find above file in my locale  but no file exist in system called as "Application data" and so on.. feeling helpless here
### Additional information
Guys  can anyone plz help me on this.. i did web search for this issue and modified many config file .. tried many possibilities  but still could not succeed..  we are trying to roll out salesforceDX in our organization.

see the screenshot below:
![image](https://user-images.githubusercontent.com/37792182/38167577-ddb9971c-3554-11e8-8e71-2893f1275822.png)

**Comment by vazexqi** [comment]
@sumitkr49 - You are trying to install the VS Code extensions into the Force.com IDE 2 instead of VS Code. Please take a look at the video at https://github.com/forcedotcom/salesforcedx-vscode/wiki to get started.

Also, these kinds of getting started questions are better asked on https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HTp1SAG

The issue queue on GitHub is reserved for bugs and feature requests.
