### ISSUE TITLE
SFDX: Authorize an Org keeps on running and browser is not opened for Authorization

### ISSUE THREAD

**Issue by Bharatummadi** [forcedotcom/salesforcedx-vscode#3833]
### Summary

I have installed the latest version of Salesforce CLI. While trying to authorize my org I have used the SFDX: Authorize an Org, however SFDX: Authorize an Org keeps on running and browser is not opening for authorization.
I have tried to change my default browser as mentioned in #1654, but it did not work either way. 

### Steps To Reproduce:

1.  Run SFDX: Authorize an Org (Using Ctrl+Shift+P)

### Expected result

The browser should be opened for authorization of org.

### Actual result

The command was running continuously and getting a timeout error.

### Additional information

![image](https://user-images.githubusercontent.com/41880719/153867650-769d9e2d-b317-4989-adf2-013eaeb79de8.png)
![image](https://user-images.githubusercontent.com/41880719/153869211-da185916-8740-4b2b-94f6-1654e56cd072.png)
Default browser settings : 
![image](https://user-images.githubusercontent.com/41880719/153869306-8cc3edab-8324-4431-bf9b-4f1a549899d8.png)

**Salesforce Extension Version in VS Code**: v53.16.0

**SFDX CLI Version**: sfdx-cli/7.137.1 win32-x64 node-v16.13.2

**OS and version**: Windows 11

**VS Code version**: 1.64.2

**Comment by Bharatummadi** [comment]
![image](https://user-images.githubusercontent.com/41880719/154098124-27cd4202-7cb0-4bd6-a7aa-6343c99c0dc3.png)
I'm facing the issue from command line as well.

**Comment by randi274** [comment]
@Bharatummadi have you completed installation of the Salesforce CLI? We do require it for some commands in VS Code as well: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm

**Comment by Bharatummadi** [comment]
@randi274 yes, I have installed Salesforce CLI as well.
![image](https://user-images.githubusercontent.com/41880719/154109645-f47e6bcb-de89-48d9-bccf-f9ae54ab863f.png)

**Comment by Bharatummadi** [comment]
@randi274 @jag-sfdc Could you please help me with this.

**Comment by jeffb-sfdc** [comment]
@Bharatummadi when you run `sfdx: force:auth:web:login` (and the other parameters you posted on 2/15), I understand that it tomes out, but could you describe what happens?

For example, what should happen, is you run `force:auth:web:login` from a CLI, a browser window opens and you see the salesforce login, you enter your credentials, and then you logged into your org, and the sfdx: force:auth:web:login process quits and you can run commands again in the CLI.

I've seen an issue where, the customer used a different means to authenticate (used a third party SAML service for authentication), which required a few page redirects, and because of this the sfdx command never got a notification that the user had successfully been authenticated.

I've also seen a case where, again, the customer wasn't using the default Salesforce authentication to authenticate into their org, and their IT department has set up their Active Directory credentials, so that once they were logged into their network, they didn't need to authenticate into their org, instead their AD credentials were used.

Do either of these scenarios sound like what takes place on your machine?

When you open a browser window, go to your org, are you presented with the Salesforce login screen?  And then after entering your credentials, go to your org?  Or do you witness something else?

**Comment by ChandrikaChukka** [comment]
I'm facing the same issue as well, what's the solution?

**Comment by carlos-apexsystems** [comment]
Some pointers: enable pop-ups for the browser and also try setting a different browser as default (the change from Chrome to Edge did the trick for me). 

Hope you get/got to solve it!

**Comment by alonakaliuzhna** [comment]
I've been facing the same issue  and I've tried changing my browser, but it still doesn't work. What's the solution?

**Comment by emapco** [comment]
Any fix or workaround for WSL?
