### ISSUE TITLE
Unable to create LWC project

### ISSUE THREAD

**Issue by NayanaGupta-Git** [forcedotcom/salesforcedx-vscode#3894]
Unable to create lWC project.

Please consider this on priority as it's stucking my work.

**Comment by gbockus-sf** [comment]
Hi @NayanaGupta-Git 
Can you provide more details please? What errors are you getting?  What OS is your machine?  
Thanks

**Comment by mohanraj-r** [comment]
@NayanaGupta-Git Can you please post the info from #3899 in this issue. Can you also provide the version of salesforce vscode extension and SFDX CLI version you are using.

**Comment by mohanraj-r** [comment]
From #3899 by @NayanaGupta-Git :

The OS in my system is  - Windows 10
<img width="758" alt="Error in VS" src="https://user-images.githubusercontent.com/64770166/157502426-907fc47a-c58e-4ecc-bd2a-6481128e20f4.PNG">

and the issue is 
When I create a new project in LWC the Default path goes to that Project and their are no files in lwc folder(.html,.js ,.metaxml).
I have attached the screenshot of the same
I have created Project Test and the lwc folder has no files.

Also Even if i set the default org on creating a new project it says 'No Default org Set'.
<img width="936" alt="Error" src="https://user-images.githubusercontent.com/64770166/157502901-4013a212-cc3e-4c09-b059-5796454db014.PNG">
