### ISSUE TITLE
Unable to create Salesforce project

### ISSUE THREAD

**Issue by vinaytejnissankula** [forcedotcom/salesforcedx-vscode#3904]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by omerfarukozdemir** [comment]
#3903

**Comment by AnanyaJha** [comment]
Hi all! Thanks for reporting this and sorry about the issues you're facing. This is due to a known problem with the latest release of the Salesforce Extensions v54.4.0. This issue is being tracked by https://github.com/forcedotcom/salesforcedx-vscode/issues/3901 and the team is working on a fix. In the meantime, please downgrade to version v54.3.0 - let us know if you see any other issues or have any questions!
