### ISSUE TITLE
Command 'SFDX: Create Project' resulted in an error (command 'sfdx.force.project.create' not found)

### ISSUE THREAD

**Issue by varundeshmukh** [forcedotcom/salesforcedx-vscode#3913]
When I try to create a new project using command palette in VS Code I get this error

Command 'SFDX: Create Project' resulted in an error (command 'sfdx.force.project.create' not found)

VS Code Version: Version: 1.65.2

OS: Mac OS Monterey 12.0.1 

Salesforce Extension Pack: v54.4.0

SFDX CLI Version: sfdx-cli/7.141.1 darwin-x64 node-v16.14.0

Node.js: 14.16.0

**Comment by AnanyaJha** [comment]
Hello! This is due to a known issue and our team has just released version 54.4.1 of the Salesforce Extensions with the fix. Please update your extensions to the latest version and reload the window to access the fix. Let us know if you continue to see any issues, thanks! Closing this thread out in favor of #3901
