### ISSUE TITLE
Extension executes Test flags that are not valid in CLI plugins

### ISSUE THREAD

**Issue by Guitarbum722** [forcedotcom/salesforcedx-vscode#400]
### Summary
Recent version of Salesforce VSCode extension 42.12.0 executes the `sfdx force:apex:test:run` with the `--tests` flag when running tests via clicking the `Run All Tests` or `Run Test` buttons directly in the editor.  However, this flag is only available in `v42` of the CLI Plugins (which appears to be a pre-release).

### Steps To Reproduce:
1. Click `Run Test` in the editor to run one specific test.
2. The extension executes this command: ```sfdx force:apex:test:run --tests TestClass --resultformat human --synchronous --loglevel error```
3. Test run fails with this response: ```Unexpected argument --tests```
4. Update CLI plugins to `42.0.20 (pre-release)`
5. Specific test runs correctly with pre-release plugins installed. 

### Expected result
I would not expect the recent version of the VSCode extension would not execute a DX command with arguments that are not valid.

### Actual result
As mentioned in Step To Reproduce, the test fails to run because an invalid argument (`--tests`) is provided.

**VS Code Version**:
1.22.2

**SFDX CLI Version**:
sfdx-cli/6.12.0-8b887b22cc (windows-x64) node-v8.9.4
VSCode Extensions 42.12.0

**OS and version**:
Windows 10

**Comment by vazexqi** [comment]
@Guitarbum722 - Curious why you say the 42.x.y versions of the Salesforce CLI is a pre-release version. Version 42 is the current stable version that coincides with the current Spring '18.

It does seem that you might have an older version of the plug-ins installed. You are on 42.0.20 even though the current one is 42.12.0 (and it will be bumped up to 42.13.0 today since Thursdays are when we do our weekly releases).

![capture](https://user-images.githubusercontent.com/54414/39310256-c8f5ae82-491e-11e8-9422-269f66775c86.PNG)

Could you try `sfdx update stable` to see what happens?

**Comment by Guitarbum722** [comment]
42.0.20 only installed if I ran `sfdx plugins:install salesforcedx@pre-release` and the output for checking the plugins version is:
```$ sfdx plugins
salesforcedx 42.0.20 (pre-release)```

**Comment by vazexqi** [comment]
@Guitarbum722 - I _think_ I know what the issue is.

What do you get when you do the following:

```
sfdx plugins --core
```
I suspect that you had previously used the pre-release before and installed it locally. Thus, it overrides whatever is in core. 

If my theory is correct, then you should do `sfdx plugins:uninstall salesforcedx` and then `sfdx update stable` and it will be back to the stable channel.

**Comment by Guitarbum722** [comment]
Excellent!  Here is the output after following your instructions.  Everything seems to be good to go.  Thanks for your help!
```
$ sfdx plugins --core
@salesforce/plugin-generator 0.0.6 (core)
builtins 1.0.0 (core)
salesforcedx 42.13.0 (core)
```
