### ISSUE TITLE
Apex Language Server throws "java.lang.NullPointerException" when using Go to Definition

### ISSUE THREAD

**Issue by dylanribb** [forcedotcom/salesforcedx-vscode#401]
### Summary
When trying to use "Go To Definition" for user-created classes, methods, etc., in files other than the current one the Apex Language Server displays the following in the Output panel:

`INFO: unexpected error during apex additional validate:
..... (code here)......
java.lang.NullPointerException`

Attempted to delete the `apex.db` file, refresh SObject definitions, and restart VS Code with the same result.

### Steps To Reproduce:
1. Open VS Code
1. Open a user-created Class
1. Try to "Go To Definition" for a method/class in another class/file
1. View Output panel

### Expected result
It should have jumped to the method definition in another file.

### Actual result
An error gets thrown in the Output panel.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.22.2

**SFDX CLI Version**:
6.12.0-8b887b22cc

**OS and version**:
macOS 10.13.4

**Java Version:**
Oracle JDK 8.0.171

**Comment by dylanribb** [comment]
I see that there was a duplicate issue already opened that seems related to the same thing.

**Comment by vazexqi** [comment]
@dylanribb - Thanks for reporting this. We will try to reproduce this. 

Quick question: you said this is a dupe. Is it a dupe of #388? In that case, was it because you were referring to SObject this way

```
List<MyObject__c> objects = new List<MyObject__c>();

but not this:
List<mynamespace__MyObject__c> objects = new List<mynamespace__MyObject__c>();
```

One thing to note (and I'll repeat myself on some of the other issues on the Apex LSP) is that the Apex parser/compiler is not designed to be an incremental parser. This means that it might not be able to recover from errors if the file you are typing is malformed (for instance it's missing a `}` that closes the construct) or if it contains types that are not around yet (for instance you reference MyNewClass, which has not been defined or if you are using an SObject but don't fetch that down using `SFDX: Refresh SObject Definitions`. When that happens, we try our best effort to parse the rest of the file, but we cannot infer things that are not there.

That being said, there could be bugs there. What we are doing now is to better distinguish those different types of errors: when something is a real error and when something is an expected error since we don't have the type you are referring to yet.

**Comment by dylanribb** [comment]
@vazexqi I hit the issue again, and one thing I've noticed that correlates to the issue is a high level of complexity for a given class/method. For example, we have a class with a "cyclomatic" complexity score of 36 (which is pretty high), meaning that we have a ton of if/else branches and it requires a bunch of tests to verify each branch. We also have another class which is fairly large (~1300 sloc). This obviously needs some refactoring on my part, I just thought it was interesting to note that the process seems to fail for particularly large or complex classes.
