### ISSUE TITLE
Not retrieving managed components alongside asterisks

### ISSUE THREAD

**Issue by jh480** [forcedotcom/salesforcedx-vscode#4437]
### Summary

"Retrieve Source in Manifest" will ignore members above or below wildcards.

### Steps To Reproduce:

1.  Write a manifest xml with both a wildcard-asterisk entry and at least 1 managed component of same type (like "ApexClass").
1.  Right-click manifest and select "SFDX: Retrieve Source in Manifest from Org".

### Expected result

SFDX should retrieve both all unmanaged components as well as the explicitely specified managed components.

### Actual result

SFDX retrieves only the unmanaged components.

### Additional information

![image](https://user-images.githubusercontent.com/113723451/190788843-cd9f59e0-f0d2-4bae-9458-9a4320017f61.png)

**Salesforce Extension Version in VS Code**: v55.8.0

**SFDX CLI Version**: sfdx-cli/7.163.0 win32-x64 node-v16.16.0

**OS and version**: Win10 Pro 21H2

**Comment by gbockus-sf** [comment]
Hi @jh480 
I think we might be encountering a limitation in the API here just reading though the Packages section [here](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/manifest_samples.htm#manifest_packages).  

A couple of sanity checks: 
1. What happens if you use sfdx from the command line to pull the same metadata from manifest? `sfdx force:source:retrieve -x path/to/package.xm`
2. How is the managed component in your org?  Is it the packaging org? Is it installed via managed package? 
3. If you remove the '*' from the manifest and only list the managed class does retrieve work as expected?

**Comment by jh480** [comment]
Hello gbockus-sf,

I'm unsure wether it's the API, seeing as a retrieve via the Ant Migration Tool retrieves both unmanaged classes and the specified managed class (or ~any other metadata type).

1. SFDX retrieves only the unmanaged components.
2. It is installed via managed package, on a Developer sandbox.
3. Yes, listing unmanaged components without asterisk will retrieve them, also together with any unmanaged (explicitely listed) components.

**Comment by jh480** [comment]
@gbockus-sf, jftr, should I have pinged you?

**Comment by jh480** [comment]
Seeing as this also fails with sfdx CLI by itself; I've decided to cut to the chase and open a bug with the CLI team.
https://github.com/forcedotcom/cli/issues/1825
