### ISSUE TITLE
Salesforce Extensions not loading for a long time

### ISSUE THREAD

**Issue by Auradha04** [forcedotcom/salesforcedx-vscode#4529]
Type: <b>Bug</b>

Not able to connect and authorize the org

Extension version: 56.3.1
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz (4 x 1796)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.96GB free)|
|Process Argv|--crash-reporter-id 96602639-8a3e-482a-b353-3981fc1a2d54|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30566497
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by gbockus-sf** [comment]
HI @Auradha04 
Can you provide a few more details?   
1. Are you able to execute the 'SFDX: Authorize an Org' command? 
2. If So does it open the browser window to authenticate with the org? Does the succeed and get you into the org? 
3. If you are able to auth do you see the username in the bottom status bar of VSCode? 
4. Are there any errors being reported? 

There is a known race condition where in some cases after auth'ing the extensions will be out of sync. This can typically be worked around by executing 'SFDX: Reload Window' and then everything should pick up the auth info.  Let me know if that was your case and the work around fixes your issue.

**Comment by Auradha04** [comment]
I am not able to run 'sfdx:authorize an org ' command

**Comment by gbockus-sf** [comment]
@Auradha04 interesting.  This could be a problem with the setup, or it could be an issue with the extensions starting up. 

1. Are there any error messages being reported? 
2. Is SFDX: Authorize an org just showing up in the command pallet at all? 
3. From the terminal in vscode: Are you able to run `sfdx auth:web:login`? [doc](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_auth_web_flow.htm) 
4. From the command pallet run: Developer: Show Running Extensions.  Is the 'Salesforce Cli Integration' extension present? 
5. From the command pallet: Developer: Toggle Developer Tools.   Is there any errors in the dev console.

I'm just trying to get enough info to narrow down where the problem is occurring. 
Thanks

**Comment by unity0S** [comment]
Hi, encountered the same problem.
1. No error messages reported.
2.It's not showing.
3.No
4.It's not present
5. Yes there are
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/29586520/199698971-563501e4-1377-489b-ac99-e699682cdb03.png)

**Comment by gbockus-sf** [comment]
Thanks for the info @unity0S.

Ok so the state you're currently is in the core extension failed to load so then all the things fall over.  

1. For not be able to run `sfdx auth:web:login` (3 above). 
  - Is sfdx present at all?  if you just run `sfdx` does it print the help message or tell you it's not found? 
  - If it is present but you can run the `auth:web:login` what is happening? Is there an error message? 
5. That definitely a bug on our side.  We updated how the extension code is bundled to control the size of the SF extensions and it appears something is off there.  

I'll mark this as a bug and we'll see if we can repo.  

@unity0S Can you also provide
**SFDX CLI Version**:

**OS and version**:


Work Arounds for this: 
First Try:
1. Command Pallet -> 'Developer: Reload Window' 
2. This might be a problem where sfdx isn't found in the path.  I'm going to test that scenario now.  We've seen that in the past when vscode is launched from an app launcher instead of the command line.  You can try opening a project from the command line using the 'code .' from the project directory.  If you haven't already you can get the code command via Command Pallet -> "Shell Command: Install 'code' command in Path"


All else fails:
1. You can revert to v55.8.0. From the extensions sidebar view there is a cog where you can select the 'install another version...' from the context menu.
