### ISSUE TITLE
Java 8 requirement error halts debugging node.js process

### ISSUE THREAD

**Issue by BrentTheBert** [forcedotcom/salesforcedx-vscode#459]
### Summary
Java 8 requirement error halts debugging node.js process. Normally when I use the debugger for node.js the debug terminal outputs some messages and you see the little control window on the top of VS Code's window. However, when I had these extensions on the little java 8 error would pop up and I wouldn't get any of the previously described debugger behavior. It wouldn't even time out and throw an error for the debugger, it was just stuck. I tried shutting down, rebooting, checking VS code versions, etc. Only turning off the SF extensions fixed it.

### Steps To Reproduce:
1. Make sure you have java 10 installed, but not java 8.
1. Disable or uninstall the SF extensions.
1. Get a node.js repo running.
1. Get the debugger to attach to port.
1. Make sure it works by adding and testing a break point.
1. Install Salesforce extentions. (https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode&tracking_data=eyJTb3VyY2UiOiJFbWFpbCIsIlR5cGUiOiJOb3RpZmljYXRpb24iLCJTSUQiOiJtcy5HYWxsZXJ5Tm90aWZpY2F0aW9ucy5yZXZpZXctdXBkYXRlZC1zdWJzY3JpcHRpb24iLCJTVHlwZSI6IkNPTiIsIlJlY2lwIjoxLCJFbGVtZW50IjoiaGVyby9jdGEifQ%3D%3D#review-details)
1. Try steps 3 through 5 again.

### Expected result
The debugger should keep functioning as usual even though SF extension doesn't have java 8.

### Actual result
Debugger stalls out, no response, made VS code sluggish or unresponsive in some cases.

### Additional information

**VS Code Version**: 1.23 which is the most recent stable build at the time of this posting.

**SFDX CLI Version**: N/A?

**OS and version**: Mac Sierra. Don't have actual version number as I'm not at work. Might update later.

**Comment by vazexqi** [comment]
@BrentTheBert - I have tried to reproduce the issue. I did this on Windows 10 instead of Mac Sierra but I don't think that matters much (if it does I can try on my Mac High Sierra when I get into the office tomorrow).

Here's a summary of what I did:

1. Uninstall Java 8 and only leave Java 10.
1. Check out https://github.com/forcedotcom/sfdx-dreamhouse
1. Launch the project and verify that the error that Java 8 is not installed shows up.
1. Add some mocha test to it
1. Launch the mocha test and debug using Attach to Process on port 9229 (the default for Node 7 and higher)
1. Verified that I'm able to connect and debug as normal.

I have a screencast of this at https://www.youtube.com/watch?v=Na50PAUxP5w to show you what I did in case you could provide more info on how this differs from your setup.

**Comment by BrentTheBert** [comment]
It appears you did the same things on windows 10 and didn't encounter it. I'll try to screencast/screenshot what I did on my Mac at work tomorrow. Thanks for putting in the effort to make that!

**Comment by vazexqi** [comment]
I'm going to close this issue due to lack of response. If the issue still persists, feel free to reopen.
