### ISSUE TITLE
Salesforce CLI Integration v56.14.0 - Error while Retrieve Source from Org

### ISSUE THREAD

**Issue by itschethandk** [forcedotcom/salesforcedx-vscode#4633]
Error deploying or retrieving source: The file or directory that you tried to deploy or retrieve isn't in a package directory that's specified in your sfdx-project.json file. Add this location to your "packageDirectories" value, or deploy or retrieve a different file or directory. For details about sfdx-project.json, see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm
14:03:43.987 Starting SFDX: Retrieve Source from Org

Metadata API request failed: Component conversion failed: FILE_ENDED

S/w versions installed - 
jdk17 nodejs14 vscode1.74 git
sfdx-cli/7.161.0 win32-x64 node-v14.21.2

**Comment by gbockus-sf** [comment]
Hi @itschethandk 
I had an internal user with this same issue recently and the issue was that she had configured a different file type for xlm other then forcesourcemanifest.  See the details in this [stackexchange](https://salesforce.stackexchange.com/questions/310526/cannot-comment-xml-file-by-default-in-vscode-salesforce-extension-pack). Did you happen to do the same thing?
