### ISSUE TITLE
"Unknown browser query" causing LWC Language Server to not load

### ISSUE THREAD

**Issue by JTScienceExchange** [forcedotcom/salesforcedx-vscode#4637]
### Summary

I am trying to configure [eslint-plugin-compat](https://github.com/amilajack/eslint-plugin-compat) by specifying a `browserslist` property in my `package.json`. When I specify a value here, the LWC Language Server fails to load with the following message

`Error [BrowserslistError]: Unknown browser query `defaults and supports es6-module``

Eventually a popup will show on vscode with the following text

`The LWC Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.`

### Steps To Reproduce:

1.  Modify the `package.json` to contain a `browserslist` property, like so:

```json
    "browserslist": [
        "defaults and supports es6-module"
    ]
```
1.  Reload vscode and observe the error message

### Expected result

The LWC Language server loads as expected

### Actual result

The LWC Language server fails to load

**SFDX CLI Version**:

sfdx-cli/7.183.1 darwin-x64 node-v18.12.1

**OS and version**:
MacOS 12.6.2

**Comment by gbockus-sf** [comment]
Hi @JTScienceExchange 
We are currently using a quite old version of the LWC compiler in the extensions.  That being the case it has an older version of browserlist (1.7.7) that doesn't support that configuration.  Looking at the source it support ```
// Default browsers query
browserslist.defaults = [
    '> 1%',
    'last 2 versions',
    'Firefox ESR'
];
```

If you use the `.browserslistrc` file to configure the more recent browserslist instead of putting the value in package.json you can work around the issue caused with the LLS. Can you give that a try (it worked for me locally).

We have it on our roadmap to get the LLS up to the date, but it's still in the planning stages at this point.
