### ISSUE TITLE
Error on Installation

### ISSUE THREAD

**Issue by chethan07git** [forcedotcom/salesforcedx-vscode#4750]
### Summary

While installing salesforce extension on windows 10 it is showing this error  "end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found:"   I am unable to solve this issue even downloaded salesforce cli and vs code again and again but couldnt work .   1   SALESFORCE EXTENSION PACK :v57.6.0   SALESFORCE CLI :sfdx-cli/7.192.2 win32-x86 node-v18.14.2     OS:Windows 10  OS BUILD:19045.2728

**Comment by simonfoden** [comment]
Hello, 

I also have this issue with macOS. Updating three Salesforce extensions failed. Uninstalling and reinstalling the entire extension pack produces the same error :

“Error: end of central directory record signature not found,end of central directory record signature not found”

Using the “Try Downloading Manually” button produces the following error : 

{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}

Corrupt files or some server hosting issue ? 

Please resolve. 

Thanks 
Simon

**Comment by randi274** [comment]
Hey @chethan07git - is this still an issue for you today? We've heard this one come up a few times, and it usually has to do with a corrupt VSIX installation coming from the marketplace. There are a few [suggestions](https://github.com/forcedotcom/salesforcedx-vscode/issues/3862#issuecomment-1055892976) in #3862 to work around this if you're still stuck, but let us know if those don't work or you need some help working through that.

**Comment by satish151994** [comment]
I'm facing the same issue end of central directory record signature not found,end of central directory record signature not found: Error: end of central directory record signature not found,end of central directory record signature not found
