### ISSUE TITLE
Unable to deploy on save (only push, but I don't want that)

### ISSUE THREAD

**Issue by JimR-FAN** [forcedotcom/salesforcedx-vscode#4813]
### Summary

My sandbox, refreshed from Prod, somehow has source-tracking turned on.   Now when I use "Deploy (or Push) On Save",  only the Push command runs -- I should be able to have Deploy run instead

### Steps To Reproduce:

1.  My developer sandbox was refreshed from Prod.   Someone turned on source-tracking on Prod.  Now my sandbox has source-tracking turned on. 
1.  Now when I save a file in VSCode, the  force:source:push command is run instead of  the force:source:deploy command.  I want the saved file to go through  force:source:deploy --  *not* push.     Even though the org has source-tracking turned on, I do not develop this way.   I like it how it used to be - that I can deploy a single file without relying on the source-tracking feature, which I am not using for this org-development project. 

**THANK YOU :-)**

### Expected result

I should be able to control whether or not  force:source:push  is used instead of  force:source:deploy.   If anything,  force:source:push should be used only on DX projects,  where my project is and always has been an org-development project.

### Actual result

When I save,  the IDE automatically runs   force:source:push   instead of force:source:deploy like it did before my last org refresh.

### Additional information

**Salesforce Extension Version in VS Code**:
v57.10.2

**SFDX CLI Version**:
v7.196.9

**OS and version**:
Windows + Chrome (lastest)

**Comment by gian-ribo** [comment]
Same Issue!

**Comment by IttesITNick** [comment]
Same issue since update of the Salesforce Extensions in VScode since yesterday.

**Comment by gian-ribo** [comment]
No problem with v57.7.0
I forced downgrade and now i can work as always. I hope for bugfix soon

**Comment by CristiCanizales** [comment]
Hello @JimR-FAN, @gian-ribo, @IttesITNick! We're sorry for that, and wanted to let you know that there is a fix in progress for this issue and we'll let you know once it's available!

**Comment by IttesITNick** [comment]
@JimR-FAN, @gian-ribo We found another workaround without downgrading the CLI.
- In setup > Dev Hub
- Disable the setting "Enable Source Tracking in Developer and Developer Pro Sandboxes"
- Then refresh your sandbox and authorize VScode again with the new sandbox.
Now on save we get deploy instead of push again.

**Comment by JimR-FAN** [comment]
Thanks @IttesITNick  - in my case I do not control Prod and am unable to refresh my sandbox.    Thank you!

**Comment by AnanyaJha** [comment]
Hi @JimR-FAN and everyone, thanks for raising this! We'll soon be releasing more changes around the deploy/retrieve experience for source-tracked orgs (including source-tracked sandboxes), so I'd like to understand a few pieces of the issue here:

-> You're seeing **all** your changed files being `Push`ed each time you save, instead of just `Deploy`ing the file you're currently working with.

-> Source-tracking is being updated for sandboxes where you don't expect to work with source-tracking, even if source-tracking has been turned on at the org level. 

If the above is what you are experiencing, would both of those changes be considered issues to you?

Background Info: With our recent changes, we started respecting the `Enable Source Tracking in Developer and Developer Pro Sandboxes` setting set at the org level - as mentioned by @IttesITNick. So if you were in a source-tracked sandbox, then you were automatically switched to the `Push` command (check out the `Push or Deploy on Save` VS Code Setting description)
But - we are working on giving you the ability to run deploys (with source-tracking enabled) on source-tracked orgs, so you'll have the ability to keep `Deploy on Save` for your source-tracked sandboxes very soon too.

**Comment by AnanyaJha** [comment]
Hi @JimR-FAN and everyone, thanks for raising this! We'll soon be releasing more changes around the deploy/retrieve experience for source-tracked orgs (including source-tracked sandboxes), so I'd like to understand a few pieces of the issue here:

-> You're seeing **all** your changed files being `Push`ed each time you save, instead of just `Deploy`ing the file you're currently working with.

-> Source-tracking is being updated for sandboxes where you don't expect to work with source-tracking, even if source-tracking has been turned on at the org level. 

If the above is what you are experiencing, would both of those changes be considered issues to you?

**Comment by JimR-FAN** [comment]
I'm not sure which message I'm replying to so here goes:
_-> You're seeing all your changed files being Pushed each time you save, instead of just Deploying the file you're currently working with_

Correct.   This is an issue for me because the extension chooses to Push instead, of  Deploy, for me.      This is an issue for me because this is not what I want.     If I did want to Push (if perhaps I changed my development strategy so that Push was my preferred method),  then I would be happy that Push was performed on Save.   But as it stands, my development strategy prefers a Deploy,  despite the fact that the sandbox may have source tracking enabled. 

_-> Source-tracking is being updated for sandboxes where you don't expect to work with source-tracking, even if source-tracking has been turned on at the org level._

Correct.   On my project,  I am not in control of Production nor the Sandbox creation.     The owners of both are free to decide to enable source tracking if they choose, but that should not force me to change my development and deployment strategy into my sandbox -- unless I am instructed to do so.   As it turns out,  even if source tracking is enabled on my sandbox,  I am free to use the org-deployment method (instead of source-push method) of updating my sandbox from my IDE.   

I am very happy to learn about the upcoming fix to give developers the option of retaining Deploy on Save, even if the sandbox they are working with has source-tracking enabled.      

Thank you!

Jim

**Comment by jmaikeru** [comment]
Imagine closing an issue without providing an ETA or confirming if it's in production yet.

**Comment by klewis-sfdc** [comment]
Hi @jmaikeru - sorry about that - this Issue is referenced in the PR that adds the setting, and looks like it got auto-closed.  The setting is merged into the develop branch and will be included in the next release.  https://github.com/forcedotcom/salesforcedx-vscode/pull/4820

**Comment by randi274** [comment]
This setting is now available with our current release, [v57.15.0](https://github.com/forcedotcom/salesforcedx-vscode/releases/tag/v57.15.0) 🎉  Since this work is now published, I'll be closing this issue, but do comment here or create a new issue with any additional feedback you have on this new setting.

To add a bit of transparency to our release process (which we've done our best to document [here](https://github.com/forcedotcom/salesforcedx-vscode/blob/v57.15.0/contributing/publishing.md#creating-a-release-branch) too), we create a new release branch every Monday, and pick up everything that was merged in the previous week. We typically release on Wednesdays or Thursdays, but the exact timing can vary since our release process still involves a good bit of manual smoke testing. If we skip a week, rest assured those changes will still go out with the next release, and we'll be sure to keep those changes linked in the release that they ship 🚢  Additionally, if you'd like to see any process changes surrounding how we communicate fixes or releases, we'd love to have you engage with us in the [discussions](https://github.com/forcedotcom/salesforcedx-vscode/discussions) tab so we can learn more about what's working or what you'd like to see changed with our open source efforts 👍
