### ISSUE TITLE
Ultra slow these days for a single class to be deployed

### ISSUE THREAD

**Issue by aman-tourlane** [forcedotcom/salesforcedx-vscode#4926]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by pibenett** [comment]
Hello

Same issue here. 

Since the 58.2.0, every deployment (class or LWC component for example) takes 1 or 2 minutes with the right click -> Deploy source to org

**Comment by ErikChase** [comment]
I am also seeing this issue.  Directly using the CLI is still quick but it appears that the extension takes an extra long time to get a response back of a successful deploy.  It should be noted that I seem to get failures responded back from the org rather quickly.  Only successes are rather slow.

**Comment by thombehrens** [comment]
I am also seeing this

**Comment by RitamAgrawal** [comment]
Hello Everyone! Can you all confirm if you are experiencing slow deployment with v57.13.1 onwards or just from v58.2.0? 

If you are experiencing slow deployment since v57.13.1, this a known issue to us. We are trying to include it in our next iteration but can't provide any estimate on timeline right now. The deployments are slowed by an internal source tracking library. We have provided a workaround (a setting) for the same. Please refer this #4885 PR description for more details.

**Comment by simon-nowak** [comment]
I was experiencing longer and longer time to deploy. Each deploy make the process a little onger. Restart VS code was fixing the problem.

And now I applied the "workaround" and everything is fine. I'm using v58.4.1

**Comment by RitamAgrawal** [comment]
Closing this issue as the progress can be tracked and workaround can be found in https://github.com/forcedotcom/salesforcedx-vscode/issues/4865
