### ISSUE TITLE
Aura Components Overrides VS Code basic Highlighting for PHP files

### ISSUE THREAD

**Issue by Hantonson** [forcedotcom/salesforcedx-vscode#5154]
### Summary

Aura Components extension on the Salesfroce Extension Pack for VS Code overrides PHP configuration, making impossible highlightinh html inside a php file .

### Steps To Reproduce:

1.  Install Saleforce Extension Pack extension on VS Code.
1.  Create a new file (Ctrl + n) and select language PHP
1.  Write "<?php echo "Hello, World!";   ?> <p>Hello, World!</p>

### Expected result

The php keywords "<?php", "echo" and "?> and the String "Hello, World!" should be highlighted. The html tags <p> and </p> should also be highlighted.

### Actual result

The php part of the code is highlighted correctly. However, the html tags are not, what makes the code creation and management difficult.

### Additional information
Code above:
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/62595545/308240f3-c978-44d0-ae31-c8964c1c3800)

More HTML:

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/62595545/8b00d5f4-af99-49b4-825e-8404f8a27e6e)

With the Aura Components Extension disabled:

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/62595545/80f1fb6e-66e4-408a-a177-1d49fa9dc4ca)

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**VS Code version**:

**Comment by gbockus-sf** [comment]
This is the same issue found in https://github.com/forcedotcom/salesforcedx-vscode/issues/1988 which has an associated WI (W-10934996)

I tracked it down the the [html grammar file](https://github.com/forcedotcom/salesforcedx-vscode/blob/93df86c8ff378182c0fdcf98fdf090c790aad051/packages/salesforcedx-vscode-lightning/syntaxes/html.tmLanguage.json#L2) in the lighting (aura) extension, which hasn't been altered in a very long time. 

Turned out this was a scope of the grammar issue.  I found a simple fix and opened a PR https://github.com/forcedotcom/salesforcedx-vscode/pull/5159

**Comment by gbockus-sf** [comment]
PR merged.  Will be included in the next release 👍

**Comment by Hantonson** [comment]
Thanks a lot!
