### ISSUE TITLE
Salesforce CLI retrieve error - Only absolute URLs are supported

### ISSUE THREAD

**Issue by omkar-kr-dev** [forcedotcom/salesforcedx-vscode#5173]
Type: <b>Bug</b>

Salesforce CLI tool throws error upon trying to retrieve the metadata

Error Message :>
Starting SFDX: Retrieve Source from Org
Only absolute URLs are supported

Extension version: 59.1.2
VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 22.6.0

**Comment by gbockus-sf** [comment]
Hi @omkar-kr-dev 
This issue comes up occasionally. There's some weird condition where the connection to the org gets out of sync.  You can get back to good by re-authing the org.  See https://github.com/forcedotcom/salesforcedx-vscode/issues/5029#issuecomment-1700473127

Let us know if the issue continues to come back and we can reopen. Thanks!
