### ISSUE TITLE
Unable to Authorize an Org in VS code

### ISSUE THREAD

**Issue by vaibhavgoud** [forcedotcom/salesforcedx-vscode#5220]
Hi,
I'm trying to Authorize an org in VS code and it's not working. It's giving the below error.

Starting SFDX: Authorize an Org

sfdx org:login:web --alias ukclmdev --instance-url https://test.salesforce.com --set-default
'"C:\Users\<userid>\AppData\Local\sfdx\client\bin\..\7.209.6-8ba3197\bin\sfdx.cmd"' is not recognized as an internal or external command,
operable program or batch file.
sfdx org:login:web --alias ukclmdev --instance-url https://test.salesforce.com --set-default
 ended with exit code 1

**Comment by daphne-sfdc** [comment]
@vaibhavgoud Can you provide the following information for us?
OS and version:
CLI version:
Extensions version:
VSCode version:

**Comment by vaibhavgoud** [comment]
Hi
Please find the below details
OS and version : windows 10
CLI version : 7.65.3.0
Extension version: 59.3.1
Vscode version : 1.74.0

Thanks!

**Comment by daphne-sfdc** [comment]
Regarding CLI version, there are 2 things that immediately stick out to me:
1. Is that what you see when you run `sfdx --version`?  I'm asking because your original error message says you are using v7.209.6 of the CLI, so you might have multiple CLI versions installed on your computer.
2. If you are indeed using v7.65.3, that CLI version is too old and no longer supported.  Please update to the latest SFDX version, which is v7.209.6.  (Which you may already have in the background, by the way, based on your error message.)

**Comment by daphne-sfdc** [comment]
Hmm interesting... In that case, please uninstall your CLI and reinstall.  The CLI team has already rolled out SF v2 in the past summer, so please consider making the switch.  If you want to stay on SFDX (which is now deprecated) you should be installing v7.209.6 (the latest version).

**Comment by gbockus-sf** [comment]
This looks like the CLI uninstalls itself issue.  Find fixes [here](https://github.com/forcedotcom/cli/issues/2447)

**Comment by gbockus-sf** [comment]
@vaibhavgoud Please let us know if the above link didn't get you fixed.  I'm going to assume that CLI issue will solve your problem.  Feel free to reopen if not the case.  Thanks!
