### ISSUE TITLE
Error on click in <script> block of a Lightning Apex Page

### ISSUE THREAD

**Issue by vgoetz** [forcedotcom/salesforcedx-vscode#5279]
### Summary
When I open an Apex Page file in VS Code and click inside a `<script> ... </script>` block, then I receive an error in the `OUTPUT` tab for `Visualforce Language Server`. 
The error only occurs if I have the `Visualforce` extension enabled (installed as recommended via "Salesforce Extension Pack").

### Steps To Reproduce:

1. Salesforce Extension Pack must be installed and enabled
1. Open a Visualforce page file (`...xyz.page`)
1. Click on a code line inside of a `<script> ... </script>` block, e.g.:
```
<apex:page id="Plot" controller="PlotController" >
    <script>
        function showError(msg) {
            return "text...";
        }
    </script>
</apex:page>
```

### Expected result
<nothing special should happen>

### Actual result
[OUTPUT] tab in VS Code shows:
```
[Error - 10:09:27] Request textDocument/documentHighlight failed.
  Message: Request textDocument/documentHighlight failed with message: Debug Failure. False expression.
  Code: -32603 
```

### Additional information
**Salesforce Extension Version in VS Code**: v59.9.0
**SF CLI Version**: @salesforce/cli/2.20.6 darwin-x64 node-v20.9.0
**OS and version**: macOS Monterey 12.7.1
**VS Code version**:  1.85.1

**Comment by mingxuanzhangsfdx** [comment]
Hi @vgoetz 

Thank you for bringing this issue to our attention. We're keen to address it effectively, and understanding its impact better would greatly help us in doing so. Could you please share more details about how this issue is affecting your experience or workflow? Any additional context you can provide will help us in prioritizing and resolving this issue more efficiently. We appreciate your help and look forward to your response.

**Comment by peternhale** [comment]
Hi @vgoetz, I found where the error is being thrown, but not sure how the visualforce language server should respond to clicks within the body of a tag or within the contents of a property.

I am logging a bug to track this issue while we continue to investigate. If you don't mind, please respond to @mingxuanzhangsfdx questions so we understand the urgency of this issue.

From the experiments I ran this morning the error you are seeing does not prevent you from pushing your source to an org.

**Comment by vgoetz** [comment]
@mingxuanzhangsfdx @peternhale 
Thx for your reply!

As you've stated, it's not that urgent as it does not prevent me from coding or pushing. 
But I've opened this issue because it's annoying / disturbing when after each click or changing the cursor position in the <script> block by moving it to the next text token/word the debug window gains focus a new error message is added. Sometimes it distracts me a little ... sometimes a lot.

**Comment by aurelien-icom** [comment]
This error seems to be avoidable by changing the file association of **.page** extension to **HTML** (in VsCode : `Ctrl+K M` or `Ctrl+Shift+P` and type "Change Language Mode").

**Comment by AndrewStopchenko-SO** [comment]
Hi @peternhale,

I just wanted to check if this issue had any movement, by any chance?..

As you correctly pointed out, the VF page can still be deployed/retrieved even with this VF Language Server errors going on, so for sure it is not a showstopper.

But the UX is very annoying.  
When you are working through some _Terminal_ panel's outputs (e.g. going through the `sf scanner` results), or checking some _"Salesforce CLI"_ outputs in the _Output_ panel (e.g. fixing some deployment errors while fixing the `sf scanner` results), clicking in any Javascript code on the VF page (either `<script>` tag, or any kind of `on<event>` handlers) fires that `Code: -32603` VF Language Server's error.  

At that point, VSCode **forcefully switches you** into the _Output_ panel and auto-selects the _"Visualforce Language Server"_ output. As a result, you are pulled away from the Terminal outputs or Salesforce CLI outputs you were working with.

This is quite distracting and it takes extra time to return to where you were - especially locating that "Salesforce CLI" item among the other 10+ _Output_ panel's dropdown options (_"here we go again..."_):
![image](https://github.com/user-attachments/assets/00ae3b1b-aa0c-43ec-92d8-93f6d928c10b)

The suggested workaround to switch to the _HTML_ language mode works in general (thank you @aurelien-icom for that!), but when in the _HTML_ language mode and trying to toggle line comments for some `<script>` JavaScript code, somehow the JS line gets wrapped into a `<!-- jsCodeHere(); -->` HTML/XML-style comment - not quite handy...

**Comment by AndrewStopchenko-SO** [comment]
Hi @peternhale, I think I found the problem.

When evaluating highlights for some javascript code embedded in the Visualforce, that JS code snippet gets copied into the `const FILE_NAME = "vscode://javascript/1"` temp 'file' , and then that temp file is sent to the `jsLanguageService.getDocumentHighlights()` method to retrieve the highlights for the clicked node (_javascriptMode.ts_, [`findDocumentHighlight()`, line 236](https://github.com/forcedotcom/salesforcedx-vscode/blob/2781e83cf9eaace4f2002c7fb31ad7b701e122d9/packages/salesforcedx-visualforce-language-server/src/modes/javascriptMode.ts#L236)).
Please notice that we pass `fileName = FILE_NAME`, and `filesToSearch = [ document.uri ]` there (_code is updated to show each param on a new line_):
```javascript
    . . .
    findDocumentHighlight: (document: TextDocument, position: Position): DocumentHighlight[] => {
      updateCurrentTextDocument(document);
      // >>>> send fileName = FILE_NAME, but filesToSearch = [ document.uri ]
      const highlights = jsLanguageService.getDocumentHighlights(
              /* fileName = */ FILE_NAME,
              /* position = */currentTextDocument.offsetAt(position),
              /* filesToSearch = */[
                      document.uri
              ]
      );
      . . .
    },
```

The `document.uri` above resolves as **original Visualforce filePath**. 

And the Typescript language server's `getDocumentHighlights(...)` function which handles this call is trying to assert that the `normalizePath(fileName)` is included in the `filesToSearch` normalized paths (Typescript's _services.ts_, [`getDocumentHighlights()`, line 2424](https://github.com/microsoft/TypeScript/blob/b263cc4b2ef12ae013526a3d8808b6716146586a/src/services/services.ts#L2424)):
```javascript
    . . .
    function getDocumentHighlights(fileName: string, position: number, filesToSearch: readonly string[]): DocumentHighlights[] | undefined {
        const normalizedFileName = normalizePath(fileName);
        // <<<< trying to ensure that the filesToSearch normalized paths include the fileName's normalized path
        Debug.assert(filesToSearch.some(f => normalizePath(f) === normalizedFileName));
        synchronizeHostData();
        const sourceFilesToSearch = mapDefined(filesToSearch, fileName => program.getSourceFile(fileName));
        const sourceFile = getValidSourceFile(fileName);
        return DocumentHighlights.getDocumentHighlights(program, cancellationToken, sourceFile, position, sourceFilesToSearch);
    }
    . . .
```

Since it doesn't find the `"vscode://javascript/1"` temporary file path in the `filesToSearch` array, this assertion fails.

#### Fix proposed:
I am no expert with TS/VSCode extensions/etc., but maybe VF language server can send two paths for highlights retrieval, e.g. `filesToSearch = [ FILE_NAME, document.uri ]`.  
However, some checks needed on how the retrieved highlights data is processed afterwards, since now the comment says _// Only one file to search above so there should only be one result_, and it only uses `highlights[0]` details.

Or, at least wrapping that call to the `jsLanguageService.getDocumentHighlights(.....)` with a try-catch block should prevent the _Output_ panel from interrupting everything to show that `Code: -32603` VF Language Server's error.
