### ISSUE TITLE
Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by AmineId** [forcedotcom/salesforcedx-vscode#5361]
### Summary

Hello,

I was trying to retrieve a profile from a Sandbox (UAT) to commit on Gitlab (Using VS Code), the retrieve run indifinetly, but when canceling i have the error Cannot read properties of undefined (reading 'type').

I tried downgrading the CLI version form 59.13.0, upgrading and downgrading @salesforce/cli with npm, Still same issue.

I have deleted the .sf and .sfdx in my system, log out of all orgs registered, then starting fresh, installing the latest @salesforce/cli 2.26 and downgrading vs code cli to 58.14.1. I Auth a sandbox (DEV) for the same project that caused the issue, I get a metadata and done. But if I try logging in to the UAT, the issue persists and nothing will ever work.

But when retrieving or executing a diff on another projet it works.

**Salesforce Extension Version in VS Code**: 58.14.1

**SFDX CLI Version**: @salesforce/cli@2.26.10

**OS and version**: Win 10 Professionnel

**VS Code version**: version 1.85.2

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/56881733/1447da35-4ffc-4815-8113-e6eb8f21b532)

**Comment by daphne-sfdc** [comment]
Hi @AmineId,
Sorry to hear that none of the workarounds we have provided work for you.

Since the VSCode extensions and the CLI both call a shared library for deploy/retrieve, I was wondering whether retrieving your profile directly from the Terminal using the CLI would result in a slow or fast retrieval time?  (If they're both slow then it's an issue inside the shared library)

The command is `sf project retrieve start --target-org=MichelinUAT --source-dir=<absolute path to your profile>`

**Comment by AmineId** [comment]
Hello @daphne-sfdc,

I tried retrieving directly with the command (I tried with a known working org SUBMGT), and I got this
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/56881733/bb457a19-4924-4b89-bfdd-c458661f966f)
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/56881733/d0b5d290-520e-4ece-9c2d-c57c8b6d3a5c)

Still the CLI is working fine on other projects, I was wondering maybe, It's something in the package that causes the issues, I'm still trying to find out...

**Comment by daphne-sfdc** [comment]
HI @AmineId, Have you seen [this issue](https://github.com/forcedotcom/cli/issues/2634) from the CLI team's repo yet?  It's a possible duplicate of what you're showing me when you run the retrieve command using the CLI.

From your screenshots, I had a few observations, which leads me to some questions:
1. When you run `sf project retrieve start` without the `--source-dir` flag to specify the file/folder that you want, the default is to retrieve every file in your org.  I'm assuming that's not what you were intending and thus a possible reason for the timeout.  Can you set the `--source-dir` flag to point to just one file?
2. Can you try increasing the wait time to 4 hours and let me know how long the retrieve command actually takes?  Add `--wait=240` to the end of your command before running it.
3. I can tell that the SUBMGT org is a Spring 24 (API version v60.0) preview sandbox.  What happens if you try to retrieve one file from a Winter 24 (API version v59.0) non-preview sandbox instead?  Is it also taking a long time?

**Comment by AmineId** [comment]
Hello @daphne-sfdc,

Sorry for my late reply.

This was an issue with our Hyperforce instance FRA8S, as all orgs in this instance were very slow in performance

see the attached picture 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/56881733/3d20728b-3bda-45ad-8984-a742495fd935)

I confirm VS Code extension SF CLI and @salesforce/cli are working correctly

For this time, I think best to close the issue, thanks for the support 👍 

Amine,

**Comment by daphne-sfdc** [comment]
Hi @AmineId, Thank you for the update.  And feel free to open a new issue if you are still facing slow deployment after the Hyperforce capacity is increased.
