### ISSUE TITLE
SFDX Retrieve is taking forever for LWC and Apex

### ISSUE THREAD

**Issue by mrinalsharma736** [forcedotcom/salesforcedx-vscode#5383]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  Create SFDX project in VScode
2. Use manifest file to retrieve Apex or LWC or simply click on any existing LWC/Apex and right click and click on 'SFDX: Retrieve Source from Org'
3. Jobs starts 

Expected result : 
Component should be retrieved within seconds

Actual result : takes more than 30 minutes

### Additional information

**Salesforce Extension Version in VS Code**: v59.15.0

**SFDX CLI Version**:  2.25.7

**OS and version**: MacOS - 14.2.1 (23C71)

**VS Code version**: 1.85.2

**Comment by daphne-sfdc** [comment]
Hi @mrinalsharma736,
Got it.  Since downgrading was not a usable workaround, please upgrade your extensions and CLI back to the latest version.

I see you have already found #4865, our long-running thread on this slow deployment/retrieval issue.  I'm going to assume you created this new issue because you have already tried all the OS-agnostic workarounds that our team proposed in that thread and none of them worked for you.  (If that is not the case, please go through that thread and try all the workarounds.)

At this point, I'm going to collect some info to help my team diagnose the issue.  My first question: What happens if you run your retrieve using the CLI in the Terminal instead of using the VSCode command?  Do you also see this slow retrieval time using the CLI?  (The CLI command is `sf project retrieve start --source-dir=<path to your file> --target-org=<your org username or alias>`)  I'm asking because the VSCode extensions and the CLI use a set of shared libraries for deploy/retrieve, and I'd like to know if the issue is in the extensions or the shared libraries.

**Comment by daphne-sfdc** [comment]
@mrinalsharma736 When you did the retrieve, did you first `cd` to the folder that contains your Salesforce project?  You should run the retrieve in the root directory of your project.
