### ISSUE TITLE
🔜  Update: Local Development Server Deprecation Notice & Announcement

### ISSUE THREAD

**Issue by AnanyaJha** [forcedotcom/salesforcedx-vscode#5501]
### **Deprecated, we are working on making a new announcement. [05.01.2024]**

Over the past few years, we've received quite a bit of [feedback](https://github.com/forcedotcom/lwc-dev-server-feedback/issues/143) on the current state of the Local Development Server; it was one of the top asks from the State of LWC Development survey in 2023. It's become very clear that the feature is not serving your needs in its current state - and it has the potential to be a productivity multiplier.

We've heard your feedback and we have some updates! **We're hard at work building a new solution for Local Development** - <safe harbor statement for forward looking functionality> - **with a goal of a Spring '25 GA**. 

This new solution will be integrated with your VS Code and Code Builder IDEs - more information will be shared soon.

In the interim, **we will be deprecating the current LWC Dev Server related commands within the Salesforce Extension Pack starting April 15th.**  The following commands will be removed from the SF Extension Pack:

- `SFDX: Open Local Development Server`
- `SFDX: Start Local Development Server`
- `SFDX: Stop Local Development Server`

As always, please share feedback and thoughts here.

**Comment by jmcnaughton-isuf** [comment]
Any suggestions or recommendations for interim substitutions? The local dev server in theory could be a real time saver like you say but there has been significant issues since December of 2022 and now we likely arent going to see anything till 2025? It would be helpful if this post was solutions oriented.

**Comment by AnanyaJha** [comment]
Hi @jmcnaughton-isuf , could you tell me more about how you or your team have been working with the local dev server currently? Our impetus here is to ensure that any available solution is working correctly and we can provide you with adequate support to resolve any issues. We've made a decision to not invest further in the current solution and instead prioritize the newer one, coming soon. 

I'll be sure to update this post with any Beta timelines in 2024 as soon as we have that info. In the meantime, it'd be helpful to understand the impact of deprecating the current local dev experience for your team.

**Comment by lukethacoder** [comment]
Looking forward to the official Local Development Server release but I really couldn't wait much longer, have sadly barely used it due to [CSS Variables not being supported](https://github.com/forcedotcom/lwc-dev-server-feedback/issues/76). Sharing because it is such a time saver when building for on-platform.

- https://lwc.garden/
- https://github.com/lukethacoder/lwc-garden
- https://stackblitz.com/edit/lwc-garden-minimal-config?file=garden.config.js

Full support for CSS Variables and anything else you could want from the modern web.

- 🚀 Local First Development (feat. Speedy HMR)
- 🧪 Mock Anything (Apex, OmniScript, 3rd Party Packages and on-platform imports)
- 🥧 `<slot/>` Placeholders
- 💅 SLDS Support OOTB (and `lightning-base-components`)
- ✏️ API Editor via Storybook-like argTypes
- 🎨 Custom Theming API
- ⚙️ Config as much or as little as your like
- 🙌 And best of all, open sourced 

![lwc-garden-arg-types](https://github.com/forcedotcom/lwc-dev-server-feedback/assets/13529535/6dfa9e87-8a62-41fe-8f64-642001b7056b)

![lwc-garden-lighting-base-components](https://github.com/forcedotcom/lwc-dev-server-feedback/assets/13529535/6a9da02d-1433-47bf-894b-6245df132a38)

**Comment by ev-will** [comment]
> @AnanyaJha The impact is pretty simple: Instead of automatic hot reloads, we have to deploy to an org, wait and manually refresh every time we make a change.
> 
> Ask one of your frontend devs how often they perform incremental updates and they'll tell you, that they perform this type of operation hundreds if not thousand times per day.
> 
> Local Development Server allowed for this - working with frontend components, you now spend more time waiting than writing code, which increases development time at least x10.

I also frequently use the Local Development Server for creating lightning components. Removing this functionality is a significant impediment to my efficiency.

As for how it was used... I would build my component out entirely using the local development server. Once I deemed it acceptable, I would deploy it to my scratch org or sandbox. I also taught all my devs to use it. In my opinion, it was an essential piece to the LWC development process. I am severely disappointed that this was deprecated without an official, alternative option.

**Comment by MohitPushpam** [comment]
Hi Is there any update related to new release as mentioned date [05.01.2024] has been passed.

**Comment by rsensharma** [comment]
**Important Update: Changes to our deprecation plans**
Remember when we mentioned plans to deprecate certain commands by mid-April? Well, after thorough testing, we’ve decided to keep them in action because they’re functioning just as they should!
However, we want to give you a heads-up on a few things to consider when using these commands. Specifically, if your Lightning Web Components include lwc:if, lwc:elseif, or lwc:else directives, you might encounter issues with the preview command. Why? Because our dev server doesn’t quite sync up with them yet.
While we won’t be issuing any fixes for this, we’ve got a brand-new solution in the pipeline slated for next year! So, stay tuned for that.
In the meantime, keep utilizing those commands and stay tuned for more updates. We’re committed to keeping you in the loop every step of the way.

**Comment by DuncanM31** [comment]
Am I missing something or are there issues with Node v20 being incorporated into the CLI, currently I am unable to install the local dev server in vscode due to the CLI running v20, when apparently it's more stable at v18, but I am unable to update to a version of the CLI where v18 is last utilised, (v2.15.9). 

How do you suppose I resolve this or is this not being monitored? Given that this is in the current trailhead iterations, I find it a bit difficult to comprehend why this issue appears to be happening.

**Comment by Alien2U** [comment]
So I spent considerable time today trying to follow the documented instructions to install the lwc local server on a new machine today. Ultimately I ended up going to npm and then a few github issues before I stumbled on this issue, where it's noted that this feature is kinda officially mostly deprecated. 

If I may, I kindly ask that Salesforce please either provide a means to use the lwc server with the latest version of the cli, or at the minimum update the installation documentation so that others can be spared the hassle.

Salesforce LWC Local Server - Installation Instructions
https://developer.salesforce.com/tools/vscode/en/localdev/set-up-lwc-local-dev

**Comment by CristiCanizales** [comment]
Hi @DuncanM31, @Alien2U. I'm on latest version of CLI and node v18.18.2 and all the commands are working fine. Could you please try same setup to verify?
<img width="618" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/5d87f956-f9f1-4e7a-a7c2-2245bf1cf362">

**Comment by VladStoyanovADP** [comment]
In the interim, we're solving this issue with https://buildox.ai
