### ISSUE TITLE
LWC LightningComponentBundle is not working  for target in vs code

### ISSUE THREAD

**Issue by thunderpycode** [forcedotcom/salesforcedx-vscode#5567]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

<target> tag should be auto suggested when creating a fresh web component

2. I am creating fresh lwc coponent using LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata"
 
<target should be populating in suggestions. although latest extensions are being installed

### Actual result

<target is not populating in suggestions. 

### Additional information

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/45660126/2b3839fc-07fe-4948-964c-81cff25026af)

**Salesforce Extension Version in VS Code**:

**Salesforce CLI Version**:  2.38.7

**OS and version**: windows 11

**VS Code version**:  1.88.1

**Most recent version of the extensions where this was working**: not workin earlier

**Comment by daphne-sfdc** [comment]
@thunderpycode Can you run `Developer: Show Running Extensions` in the command palette and send us a screenshot of what's there?  We would like to ensure you have the latest version of the extensions installed and activated.

Can you also send us any error messages you see in the following places?
1. Problems tab
2. Output tab under the `LWC Extension` dropdown option
3. Run `Developer: Toggle Developer Tools` from the command palette

**Comment by thunderpycode** [comment]
Hello @daphne-sfdc , Below are the screenshots for:

**`1. Developer : Show Running Extensions`**

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/45660126/5cb751b6-ca6b-46c3-94b7-3c45d74490d8)

`**2. Developer : Toggle Developer Tools**`

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/45660126/4db8b3d6-eed0-45c5-84fc-f1942a00a710)

`**3. Problem with created testfile**`

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/45660126/92d29edd-5bbe-4fd1-ac74-d86a38c9ca74)

**Comment by daphne-sfdc** [comment]
@thunderpycode Ah, I see the problem now.  XML autocompletion in `.js-meta.xml` files requires the Red Hat XML extension, which is included in the Salesforce Extension Pack Expanded but not the Salesforce Extension Pack.  When I didn't have the Red Hat XML extension installed, I had the same problem of `target` not populating in suggestions.

I went to the Output tab, selected `LWC Extension` from the dropdown, and found this:
![Screenshot 2024-05-03 at 9 28 15 AM](https://github.com/forcedotcom/salesforcedx-vscode/assets/139700604/649f13c5-ebbb-4b80-9f3a-460aef4d79b0)

After I installed the Red Hat XML extension and reloaded the VSCode window, the autocompletions appeared. 🙂 

Please install/enable the Red Hat XML extension and let us know if your issue is now resolved!

**Comment by daphne-sfdc** [comment]
@thunderpycode As an aside, the problem with the created LWC test file that you showed in that screenshot is a known issue.  We already have a bug logged for that, and we are hoping to get the issue fixed soon. 🙂

**Comment by thunderpycode** [comment]
@daphne-sfdc The Red Hat XML is still not working. lets follow the issue.

**Comment by peternhale** [comment]
@thunderpycode just curious what is the list of all the extensions active for this project?

**Comment by thunderpycode** [comment]
@peternhale I have already shared: https://github.com/forcedotcom/salesforcedx-vscode/issues/5567#issuecomment-2092309052

**Comment by thunderpycode** [comment]
@peternhale 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/45660126/e0a8a281-3c46-4c9c-8275-daacefd1fd11)
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/45660126/cf9639b2-053f-4e38-a05c-c560c79321f1)
![Uploading image.png…]()

**Comment by daphne-sfdc** [comment]
Hi @thunderpycode, The issue is that your Red Hat XML extension is stuck on Activating.  You will only see the autocompletions if the Red Hat XML extension is in Activated state.

Can you try the solution provided at https://github.com/redhat-developer/vscode-xml/issues/909 to reinstall the Visual C++ redistributable?
