### ISSUE TITLE
Use `extensionPack` instead of `extensionDependencies` property for defining pack

### ISSUE THREAD

**Issue by sandy081** [forcedotcom/salesforcedx-vscode#562]
From release v1.26, defining an Extension Pack now uses a new property called `extensionPack` instead of `extensionDependencies` in package.json. This is because extensionDependencies is mainly used to define functional dependencies and an Extension Pack should not have any functional dependencies with its bundled extensions and they should be manageable independent of the pack. 

So please use `extensionPack` property for defining the pack.

For more details refer to [Release notes](https://code.visualstudio.com/updates/v1_26#_extension-packs-revisited)

**Comment by vazexqi** [comment]
@sandy081 - Is the new `extensionPack` key only available to v1.26 and above? Or can this also work with older versions? Basically do we need to update our package.json to say 

```
"engines": {
  "vscode": "^1.26.0"
},
```

We are asking because our current dependency is on version 1.23 for API functionality and we want to determine if we need to bump everything up to 1.26 to take advantage of this new `extensionPack`.

**Comment by sandy081** [comment]
@vazexqi Good question, yes you have to set your engine > 1.26.0
