### ISSUE TITLE
Push errors of Classes

### ISSUE THREAD

**Issue by Shokhan** [forcedotcom/salesforcedx-vscode#568]
Error happens after several pushes of the same class,  but it compiles successfully in Dev Console. To make class compile it's necessary to use dev console and then pull it to project.
Is it config issue of vs code or sfdx?

[push error of classes (1).zip](https://github.com/forcedotcom/salesforcedx-vscode/files/2296749/push.error.of.classes.1.zip)

**Comment by Shokhan** [comment]
What kind of information you need?

**Comment by vazexqi** [comment]
@Shokhan 

Just from the video (it's hard decipher everything since there is no voice or description), it seems that the error is because of some error with either

1. Task - Task Layout.layout-meta.xml
1. Some operations with the server
1. Some operations with the server

Here are some questions:

1. How did you get the source into VS Code? Is it from an existing Git repository?
1. How did you get your source into Dev Console? Is it from doing a successful `sfdx force:source:push` from VS Code? Or does the source already exist?
1. Could you copy-and-paste the ErrorId from your screencast?
1. What happens if you do `SFDX: Push Source to Default Org and Override Conflicts`?

My suspicion is that there is some state that is not in sync – you could have made some changes in the org that is not being pulled back into VS Code so when you deploy it's not a full deploy (some things are missing).
