### ISSUE TITLE
Using VS Code Salesforce Extension Pack is too slow to retrieve or deploy code 

### ISSUE THREAD

**Issue by sergiopedrazaj** [forcedotcom/salesforcedx-vscode#5854]
### Summary

I am using VS Code with the Salesforce Extension Pack. When I deploy or retrieve a single source, it takes more than a minute or two to do so. 

### Steps To Reproduce:

1.  Find the file you want to retrieve or deploy in the explorer.
2. Secondary click on the file and click "SFDX: Deploy this source to Org" or "SFDX: Retrieve this source from Org".

### Expected result

The file should be deployed/retrieved within seconds.

### Actual result

The file is deployed/retrieved after several minutes.

### Additional information

**Salesforce Extension Version in VS Code**: 61.12.0

**Salesforce CLI Version**: 2.57.7

**OS and version**: Windows 11

**VS Code version**: 1.93.1

**Most recent version of the extensions where this was working**: No record.

**Comment by diyer** [comment]
@sergiopedrazaj Thank you for filing this issue. Can you answer few more questions for us?
- What is the behavior when you deploy/retrieve the same file using cli command (instead of vscode)
- Do you see this slowness specific to a file or metadata?
- Is this specific to a org or irrespective of any org you experience the slowness?
- Can you provide us with the org Id ? This will help us see if there is any slowness on server side.

**Comment by sergiopedrazaj** [comment]
Thanks for addressing this.

- Using cli command is slow too. 
- All files show the same slowness.
- It seems to be specific to one org: 00DO90000098btF a file took 1 minute 47 seconds to deploy. Tried on a different dev org (same file) and it took 22 seconds to deploy.
- The org Id with long waiting times: 00DO90000098btF, Instance USA270S

Thank you!

**Comment by CristiCanizales** [comment]
hi @sergiopedrazaj, we'll do some research with those details. In the meantime, could you check if you have `Perform Synchronous Compile on Deploy` Apex Setting enabled or disabled? Sometimes having it enabled makes deploy take longer. Another thing to try is delete `.sf`/`.sfdx` folders, re auth to your org and try again. Let me know if that's it.
<img width="317" alt="image" src="https://github.com/user-attachments/assets/ca1741bc-9cb0-4a97-8776-f9e4342b777b">

**Comment by sergiopedrazaj** [comment]
Hi, @CristiCanizales . Thank you so much!
I unchecked the Compile on Deploy setting and the wait time has reduced significantly.
It is a Full Sandbox and we recently refreshed it, but on previous refreshes we did not have to uncheck this setting. 

I am attentive to further steps.

**Comment by CristiCanizales** [comment]
Hi @sergiopedrazaj, glad that helped. Here's the [setting's](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_deploying.htm#:~:text=This%20feature%20causes,continuous%20integration%20processes.) documentation in case you want to review it and decide accordingly if you want to keep the setting disabled. I'd also like to know recent was the refresh? Because that could also explain the slowness. On previous refreshes, did you also attempt to deploy soon after the refresh?
