### ISSUE TITLE
[Apex] Symbol information not provided to VS Code in v61.16.0

### ISSUE THREAD

**Issue by ImNotARealUser** [forcedotcom/salesforcedx-vscode#5884]
### Summary

On my machine, with the latest updates to the Apex extension, symbols are no longer provided in Apex files so that features like "Outline" and "Go to symbol in editor (e.g. <kbd>Ctrl</kbd> + <kbd>R</kbd> [on my machine] to jump to method, class, property)", "<kbd>F12</kbd> into method", etc., do not work. I've had to revert to an earlier version of the extension to continue to use these heavily relied upon features.

with v61.16.0:

![image](https://github.com/user-attachments/assets/80a0b394-85ab-4833-9c18-1f1de6200c80)
![image](https://github.com/user-attachments/assets/4a71d683-bdd9-4487-bd6f-10b1db01c2ad)

with v61.12.0 I have no issues and see they symbols and outline that I'd expect.

### Steps To Reproduce:

1.  Install the latest version of VS Code.
2. Install the latest version of the SF Extension Pack, including Apex v61.16.0 (released yesterday) or 61.15.0 (released a week ago).
3. Open a .cls file and attempt to view the file's outline, F12 into a method, or use the "Go to symbol in editor" command from the command palette. 

### Expected result

Should be able to see outline, jump to methods, navigate through code, etc.

### Actual result

These features are not working (see above screenshots).

**Salesforce Extension Version in VS Code**: v61.16.0
**Salesforce CLI Version**: `sfdx --version` = `sfdx-cli/7.209.6 win32-x64 node-v18.15.0`

**OS and version**: Windows 11

**VS Code version**: 1.94.0

**Most recent version of the extensions where this was working**: v61.12.0

**Comment by daphne-sfdc** [comment]
Hi @ImNotARealUser,

We no longer support SFDX v7 CLI, which is deprecated.  Please uninstall your existing CLI using the instructions here: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm Then reinstall the latest version of SF v2 CLI.

**Comment by ImNotARealUser** [comment]
So the outdated CLI version is definitively the reason for this issue? We have a lot of automated scripts that are painstaking to update which rely on now deprecated CLI commands, so we've been putting off updating them. However, if the Apex extension relies on the CLI we will have to make the change.

**Comment by daphne-sfdc** [comment]
You're right that the commands you're looking to do, such as viewing the file's outline and F12 into a method, do not depend on the CLI.  However, there are features in the Apex extension that do depend on the CLI, and those will soon be incompatible with SFDX v7.  Here's why:

The Apex extension depends on the CLI Integration extension in that some commands such as Run Apex Tests do not work without an org.  You would need to first use the CLI Integration extension to authorize to an org and deploy the contents of your project to that org.  Currently, a lot of SFDX v7 commands are mapped to SF v2 commands - e.g. `force:source:deploy` maps to `project:deploy:start` and `force:apex:test:run` maps to `apex:run:test`.  However, the CLI Team is phasing out this feature soon as more and more customers switch from SFDX v7 to SF v2, so eventually you will be required to do the SFDX -> SF transition.  (If you are using SFDX v7, you will get a command not found error when you run `sfdx project:deploy:start` and `sfdx apex:run:test`.)

To try to resolve the current issue that you reported, I suggest you try removing all versions of your Salesforce extensions from your computer and then reinstalling the latest version.  Here's how to do that:

1. Quit VSCode
2. Open a new Command Prompt window
3. `cd .vscode`
4. `cd extensions`
5. `for /d %i in (salesforcedx*) do rmdir /s /q "%i"`
6. Open VSCode and reinstall the Salesforce Extension Pack

Let us know if that resolves your issue!

I want to repeat that we strongly encourage you to make the SFDX -> SF transition as soon as possible so that you can continue to use the latest version of the CLI and extensions with all the latest features and bug fixes.  As you pointed out in your comment, you're going to have to do it later anyway, so it would be a good idea to do it before the deadline when essential commands stop working.

**Comment by ImNotARealUser** [comment]
Thanks very much for the detailed response. We've been able to update all of our old `sfdx` style commands and upgraded to the latest version of the CLI. Additionally, I've reinstalled all the SF extensions and things are working correctly now. So we're all set - thanks again!
