### ISSUE TITLE
SFDX: Authorize an Org (Allow Selection of Org Login Url)

### ISSUE THREAD

**Issue by JimBTek** [forcedotcom/salesforcedx-vscode#610]
### Summary

Difficult / impossible to follow the wiki:
https://github.com/forcedotcom/salesforcedx-vscode/wiki/Develop-Against-Any-Org-in-Visual-Studio-Code

to Auth to a Sandbox from within VSCode

### Steps To Reproduce:

1.  Follow the wiki article
1.  run `SFDX: Authorize an Org` command in VSCode
1. enter a sandbox username
1. it takes you to login.salesforce.com

### Expected result

either it intelligently selects the domain, or switching the domain works

### Actual result

* tried using custom domain without much luck
* tired passing argument `-r https://test.salesforce.com` without luck

### Additional information

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by vazexqi** [comment]
Agreed. This is a usability issue. We need to work on this to make this simpler.

@JimBTek - For now, could you edit your sfdx-project.json to include "  "sfdcLoginUrl": "https://test.salesforce.com".

This is documented at https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm

@ntotten or @ruthemmanuelle - We probably want to add that to the wiki

Some possible suggestions would be to augment `force:project:create --manifest` with the template option to be `production` or `sandbox`. In the `sandbox` case then it will add the `  "sfdcLoginUrl": "https://test.salesforce.com"` for you. Then we can augment the VS Code side to make those options available.

**Comment by ruthemmanuelle** [comment]
Since @ntotten is on vacation this week, I went ahead and updated the wiki to add info on how to update the login URL so you can authorize a sandbox org: 

https://github.com/forcedotcom/salesforcedx-vscode/wiki/Develop-Against-Any-Org-in-Visual-Studio-Code/_compare/38076ff10814ede6f0af3df4247f74cc3f354c11...1811ac26ee77acec3e0cff47d8ad0263656ed33b

Thanks for the heads-up, @vazexqi , and thank you for reporting this, @JimBTek .

**Comment by evanmcd** [comment]
@vazexqi I'm getting an error when running the Authorize an Org command:

`Unknown config name "sfdcLoginUrl"`

**Comment by evanmcd** [comment]
@vazexqi Also, I've been unable get connected to my sandbox since doing so the first time (after I remove the sfdcLoginUrl preference).

I run `sfdx force:auth:web:login -r https://test.salesforce.com` and successfully login via the browser, then see the 'Successfully authorized' message in my terminal, but my sandbox username does not appear in the status bar, and the Refresh and Deploy options never appear in my menus.

Would you like me to submit a separate issue for this?

Happy to help troubleshoot in any way I can. 

Thanks.

**Comment by ruthemmanuelle** [comment]
@evanmcd - Is the `sfdcLoginUrl` property at the top level of your `sfdx-project.json` file? For example:

```
{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    },
    {
      "path": "unpackaged"
    },
    {
      "path": "utils"
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://test.salesforce.com",
  "sourceApiVersion": "44.0"
}
```

**Comment by evanmcd** [comment]
@ruthemmanuelle sorry for the delay. Yes, I do have it at the top level as you've shown.

**Comment by amphro** [comment]
@evanmcd The error `Unknown config name ...` comes from using `sfdx force:config:set`. You can not use `sfdcLoginUrl` as a config variable. Instead, that needs to go in your `sfdx-project.json` file. If you want to set a config var, you can try `sfdx force:config:set instanceUrl=https://test.salesforce.com`. I think the auth commands will use the following order: 

1. `--instanceurl` flag on the commands
2. `sfdcLoginUrl` in the `sfdx-project.json` file
3. `instanceUrl` in `force:config:set`
4. SFDX_INSTANCE_URL envvar

**Comment by evanmcd** [comment]
Ahh thanks @amphro. My mistake for having it in the wrong file. I can now auth with an org successfully. Thanks for your help.

**Comment by ntotten** [comment]
The implementation should be as follows:

1. SFDX: Authorize an Org
2. The VS Code selection UI prompt for the Org type (Sandbox, Production, Custom)
3. If sanbox or prod are selected the login command is run against the default url for those types 
4. If custom is selected a text box dialog is shown for the user to type in the domain

These changes dont update the sfdx-project.json file.

**Comment by amphro** [comment]
Production is the default. We talked about having a `--sandbox` on the auth commands so users don't need to type in the sandbox url. I think that could be a good option to help support this from the CLI side. Custom would obviously just use the `--instanceurl` flag.

**Comment by reddy12swetha** [comment]
Hi I am having issues authorizing sandbox org, the issue i run into is 
Kill the process running on port 1717 or use a custom connected app and update OauthLocalPort in the sfdx-project.json file.
need some inputs troubleshooting this error

**Comment by troveryor** [comment]
@reddy12swetha I had the same error yesterday. For me it was part of a new project build using SFDX: Create Project with Manifest. ( originally I hadn't updated my sfdx-project.json to point at test.salesforce.com).

When I got to the authorize org step, the browser login page was redirecting to an old URL for my sandbox. It had been refreshed since my last login, and the server instance had changed.  I was able to resolve it by using the "Login with a different user name" link when I retried the authorize command.

**Comment by smolinari** [comment]
I am also finding this error, where if I change the `sdfx-project.json` file to the test URL, it still goes to the login URL. If I then manually change to test in the browser, it redirects incorrectly and the org isn't authorized. 

Needless to say, this workflow has a lot of room for improvement. 

Scott

**Comment by smolinari** [comment]
@JimBTek - You mean that isn't possible now? I'm brand new to SFDX. Would you be so kind and explain the process to get changes made locally with SFDX into production?

Scott

**Comment by JimBTek** [comment]
@smolinari it's possible now in SFDX for sure. But you can't easily do so within the VSCode UI completely, you have to jump back and forth with terminal, especially to switch orgs. And its hard to do both sandboxes and production because the URL is different and you may have to tweak a json file. 

But i think Aliases help.

**Comment by smolinari** [comment]
Ok. I'll just have to do some trials and errors. 👍 

Scott

**Comment by ntotten** [comment]
This will ship in our next release. :)

**Comment by anip12** [comment]
I found the Best solution which i have found it randomly : only you have to do is to make the path in environment variable of the bin folder of the vsCode eg: C:\Program Files\Microsoft VS Code\bin
now after this ur vs code authorise an org will work properly .
