### ISSUE TITLE
Support execution of anonymous Apex via SFDX

### ISSUE THREAD

**Issue by muenzpraeger** [forcedotcom/salesforcedx-vscode#66]
### Functionality
To simplify executing anonymous apex (not using sfdx from the built-in VScode terminal window) a custom command should be implemented.

### Implementation

* A new menu binding "SFDX: Execute Anonymous Apex" will be implemented. Also a menu addition (in "editor/context" for .cls and .trigger files).
* Input will be saved in temp file with random file name.
* Anonymous Apex command gets executed and temp file deleted. Output gets send to standard "Output" console window.

**Comment by vazexqi** [comment]
@muenzpraeger - Thanks for raising this issue. This is definitely on the roadmap.

* [Agreed] A new menu binding "SFDX: Execute Anonymous Apex" will be implemented. Also a menu addition (in "editor/context" for .cls and .trigger files).
* Input will be saved in temp file with random file name - _Is this because the execute anonymous only takes input from a file or from standard io in an interactive manner? Would it help if the execute anonymous apex command took input directly from stdin?_
* Anonymous Apex command gets executed and temp file deleted. Output gets send to standard "Output" console window. - _Do we want to results to be outputted to the output console? Or do we want to open it in a new tab?_

@kaplanjosh - Would be interested to hear your thoughts on this from a product perspective.

**Comment by muenzpraeger** [comment]
@vazexqi I PR'd it already. ;-)

https://github.com/forcedotcom/salesforcedx-vscode/pull/72

**Comment by vazexqi** [comment]
@muenzpraeger - Yup, I saw :-) I was thinking of keeping the high-level design requirements/specifications to this thread and then the specific implementation details on the PR itself. I would like to hear from @kaplanjosh on what his vision is for this command.

**Comment by muenzpraeger** [comment]
And yes, input from a file b/c the CLI takes file as an input.

Output: Mostly it's IMHO sufficient to have it in the output console. Otherwise a HTML output (maybe "equal" to what I [suggested for SOQL](https://github.com/forcedotcom/salesforcedx-vscode/issues/65)) would be sufficient.

**Comment by vazexqi** [comment]
Closed via #152
