### ISSUE TITLE
Missing 'engines' key in package.json of salesforce-utils-vscode in develop branch

### ISSUE THREAD

**Issue by muenzpraeger** [forcedotcom/salesforcedx-vscode#68]
### Missing 'engines' key in package.json of salesforce-utils-vscode

The develop branch cannot be used for launching the extensions. An error is raised that points to a missing engines key in the package.json of salesforce-utils-vscode.

Adding the key raises another error:
/.../salesforcedx-vscode/packages/salesforcedx-utils-vscode]: properties `activationEvents` and `main` must both be specified or must both be omitted

Removing the main key from the package.json solved that issue.

### Steps To Reproduce:
* Clone the repo, make sure that you're in the develop branch.
* In VS Code, open the debug view and from the launch configuration dropdown, pick "Launch Extensions".
* The new VS Code windows opens with an error message.
* Add engines key to package.json:
* Re-launch from debug view - new error message appears.

### Expected result

Launching the extensions without an error message.

**Comment by vazexqi** [comment]
Yes, thanks for the fix. It's not a blocker but it's not a good experience the error for a developer.

The error can be ignored since that package (salesforcedx-utils-vscode) is not a VS Code extension and won't ship as such.

It's a consequence of the debug configuration loading everything under the /packages directory even if it is _not_ an extension.

**Comment by muenzpraeger** [comment]
That's why I commited it. I was scratching my head why the error showed up in a fresh installation. ;-)
