### ISSUE TITLE
ERROR:  The metadata retrieve operation failed: LIMIT_EXCEEDED: Too many files in retrieve call, limit is: 10000.

### ISSUE THREAD

**Issue by leosfdc** [forcedotcom/salesforcedx-vscode#685]
### Summary

Trying to pull the files to local folder from package.xml using sfdx force:source:retrieve

### Steps To Reproduce:

1. sfdx force:source:retrieve command

### Expected result

Should have fetch all the types mentioned in package.xml

### Actual result

got an exception with
ERROR:  The metadata retrieve operation failed: LIMIT_EXCEEDED: Too many files in retrieve call, limit is: 10000.

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/35933829/47182758-4e299000-d2f4-11e8-8443-8e47e4c33ffb.png)

**VS Code Version**:  latest version just updated before performing this operation

**SFDX CLI Version**: latest version just updated before performing this operation

**OS and version**: windows 10

**Comment by ntotten** [comment]
This is by design. I am going to keep it open to track it, but the work around is to retrieve less files. If you absolutely must have a project with that many files, you will need to create multiple package.xml manifests and do seperate retrieves/deploys to keep the total number per operation to less than 10,000. That being said, we do not recommend creating projects that big.
