### ISSUE TITLE
xml files have useful links to other xml files

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/salesforcedx-vscode#827]
**Is your feature request related to a problem? Please describe.**
when working with .xml files, there are often links (to profiles, fields, objects, flexipages, etc)

**Describe the solution you'd like**
When looking in .xml files, if we know from the mdapi schema that something is a link, and can be resolved locally, we link it in vscode.  

In the picture below, `Entry_Record_Page` is a file in the flexipage folder.  It'd be nice to be able to follow that link.
<img width="771" alt="screen shot 2018-12-17 at 1 44 50 pm" src="https://user-images.githubusercontent.com/4261788/50111367-41e18680-0202-11e9-9d04-6939e99c341c.png">

Each of these items on CompactLayout is a field
<img width="615" alt="screen shot 2018-12-17 at 1 48 32 pm" src="https://user-images.githubusercontent.com/4261788/50111484-7ead7d80-0202-11e9-979f-0d1e5815cd0d.png">

This should link to a quickAction
<img width="618" alt="screen shot 2018-12-17 at 1 50 49 pm" src="https://user-images.githubusercontent.com/4261788/50111637-ce8c4480-0202-11e9-9162-5e5275f6b963.png">

**Describe alternatives you've considered**
cmd-p searching the files by name and scrolling down the correct one and opening it

**Comment by vazexqi** [comment]
@lcampos This requires a language server for these files. The downside is that each one is  a separate file with a different schema – it's an unfortunate consequence of us not settling on a canonical naming/symbol scheme for our metadata files. 

We probably should prioritize and see which files are used the most and write language servers for them.

Since these files are just XML (no need for Java unlike Apex), we might be able to write these servers in TypeScript and take advantage of https://github.com/Microsoft/lsif-typescript This could be a way to combine all of them together.

This is not a small project. If we prioritize this we can come up with a scheme to address this piecewise though and provide value with each monthly release.

**Comment by ntotten** [comment]
I am going to close this. It is a good idea, but since it is implemented in the XML language service this would be a major undertaking that we are unlikely to get to in any reasonable time period.
