### ISSUE TITLE
Investigate Malfunction after Update

### ISSUE THREAD

**Issue by ntotten** [forcedotcom/salesforcedx-vscode#844]
Let's revisit this issue: https://github.com/forcedotcom/salesforcedx-vscode/wiki/Troubleshooting#extensions-malfunction-after-update

It has been some time and VS Code has gone through updates. People seem to still be having the problem. We should at least find a way to warn people with an actionable error message if this happens.

See: https://twitter.com/jodiem/status/1079542512237203456

**Comment by JodieM** [comment]
OK, so some background here if I may. 

I decided to try and see what this VS Code thing was all about, since we can now work with Sandboxes, and decided that I would document my progress becuse I'm sure there are others out there that are not developers but can benefit from VS Code and since it is now the offical tool now is the time (and I had previously done similar for MavensMate). 

So, struggling along through many old resources I got my VS Code set up (I had a lot of issues trying to work out my SSH with bitbucket but that was my own bitbucket setup and not something regular non devlopers would face). 

Then I got to the error I tweeted Nathan about https://twitter.com/jodiem/status/1079542512237203456 which I finally fixed by going through your excellent troubleshooting document. Thanks! 

So then I was set. I could do things! Great. So I started to document what I was doing. https://tddprojects.atlassian.net/wiki/x/AYB5Iw. I thought this was great and I was finally getting somewhere. But, since I had had so many stops and starts installing my dev environment (I did have it installed earlier in the year but I had to get a new Laptop becuase it failed), I needed to document the process for others who may want to get up and running simply. 

Next, I unistalled EVERYTHING and reinstalled - and videod me doing it. Boy did that take some time. https://tddprojects.atlassian.net/wiki/x/EYB6Iw. And then disaster struck! I am now stuck. I have tried to re-open #742 to deal with my current issue where the SFDX commands just don't run from the command palette. I don't think it's a PATH issue - see my comments there. 

I don't know if you want to watch my whole video to see where I went wrong in installing - maybe I should have restarted the PC at some point. But I think we are just missing some basic step by steps on how to get up and running smoothly (I added the optional components of bitbucket and source tree though), AND on Windows. So much of what I've seen just assumes that a) you are a developer and just know this stuff b) you are on a mac and just know bash intuitively or c) you already have everything installed and just need to install the extensions. 

Since so many more people will be using VS Code in the coming months, it would be great if you can provide a bit more guidance to us non devlopers. Thanks! (And if someone can help me out on #742 that would be fab).

**Comment by trebleCode** [comment]
@JodieM @ntotten 
I had similar 'command not found' issues with the extensions, and in order to fix, I commented out the:
`"salesforcedx-vscode-apex.java.home":`
line in my user preferences JSON, saved, and restarted VS Code, and stopped getting those errors. I'm not sure if commenting that out breaks things for the Apex plugin, but wanted to bring it to light.

**Comment by trebleCode** [comment]
Cheers @JodieM
I'm watching #742 as we are having similar issues. Hoping @lcampos can replicate and push an update once the problem with they key is identified

**Comment by lcampos** [comment]
Closing since the fix was released as part of `v44.16.0`, PR #868
