### ISSUE TITLE
Can only see the Create Project, Create Project with Manifest and Create ISV Debugging options unless I ALSO have a VSCode Workspace created in the same directory

### ISSUE THREAD

**Issue by geoffrothman** [forcedotcom/salesforcedx-vscode#900]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `44.17.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.2`

I've spent over 7 hours troubleshooting this and learning way too much about the underworks of VSCode :( In *every* trailhead and "how to" guide for VSCode and SFDX, you need to put a HUGE disclaimer that you have to actually create a workspace in the same directory as the sfdx-project.json file...IMHO you should take the "activationEvent":"workspaceContains:sfdx-project.json" requirement out of here because not everyone wants to have to create a VSCode workspace just to use SFDX commands in a repo :(

:warning: We have written the needed data into your clipboard. Please paste! :warning:

![image](https://user-images.githubusercontent.com/4984045/51714211-2a17d200-1ffa-11e9-9682-8f1718831ec0.png)

![image](https://user-images.githubusercontent.com/4984045/51717724-9f3dd400-2007-11e9-9369-58d07359c460.png)

**Comment by geoffrothman** [comment]
@ntotten no, not the sfdx-project.json file. In *addition* to the sfdx-project file, the code is also looking for an existing VSCode Workspace file before it will show any more than just those three sfdx options. I don't think I should have to create a VSCode Workspace just to get the SFDX commands to show up.

**Comment by lcampos** [comment]
I see what you mean now. There's a bit of confusion here because of how vscode defines what's a workspace and what it means when you use vscode apis (e.g. workspaceContains:sfdx-project.json).
In vscode, a workspace is just a file that stores links/pointers to other folders across your hard drive. You can think about it as a collection of folders that represents a project. This can then be used by vscode to open all of those folders at once under one vscode window instead of having one window per folder. Another thing that can be done is to define settings specific to a workspace e.g. which extensions are enabled/disabled, their configuration, etc.

For the salesforce extensions, we do not require you to create a vscode workspace in order for the commands to work. The only thing we need is for the folder/project you open to contain that `sfdx-project.json` file.

Specifically to the api you mentioned (activationEvent:workspaceContains:sfdx-project.json), if you do not define a vscode workspace then vscode will just "assume" you are working on an undefined workspace and work out of the folder/project you chose to open. Then, if we find that `sfdx-project.json` file in the folder/project, the extension will get activated and a .vscode folder will be added at the top level of the folder/project you opened together with a `settings.json` file that will be used to store the extension configurations you might want to create.

It's important to mention that using the sfdx create project commands will create all the needed folders and files for the extension to work.

Seeing only three sfdx commands in the command palette will happen when you haven't opened a folder/project or when the folder/project that's open is not recognized as an sfdx project, which really means it does not have a `sfdx-project.json` file at the top level.

Hope this helped clarify how the extensions work. I'm also attaching some screenshot that illustrate the scenarios I just described.

**Nothing open:**
![no_open_project](https://user-images.githubusercontent.com/1041842/51962550-56c25400-2415-11e9-9075-8b7d32eac0e1.png)

**Empty project with sfdx-project.json file**
![empty_project](https://user-images.githubusercontent.com/1041842/51962553-5c1f9e80-2415-11e9-8e1c-b13bde93725b.png)

**Normal sfdx project**
![sfdx_project](https://user-images.githubusercontent.com/1041842/51962582-79546d00-2415-11e9-8880-9ef1adeb1026.png)

**Comment by lcampos** [comment]
I'm closing this since there's nothing actionable, feel free to re-open if needed.
