### ISSUE TITLE
SOQL Grammar & Language Server

### ISSUE THREAD

**Issue by ntotten** [forcedotcom/salesforcedx-vscode#947]
The most basic requirement to enabling better SOQL query experience is to create a SOQL Language Server. This language server will provide code completion for keywords, tooling metadata, and standard metadata. It should surface information to the user about field types so that the developer can more easily build queries.

It would be ideal if the SOQL LSP provided dev time hints for creating valid queries. For example, if a developer created a WHERE clause comparing a field of type Boolean with a number, the LSP should surface that as an error.

The language server should work inside all areas developers interact with SOQL - Apex Classes, Anonymous Apex, as well as files with the .soql extension.

A separate grammar should be created for SOQL to provide high-quality syntax highlighting for SOQL.

The Apex LSP and Grammar would need to be updated to utilize SOQL.

**Comment by sc5148** [comment]
What is the current status of this? When is this going live?

**Comment by ntotten** [comment]
No ETA at the moment.

**Comment by ChuckJonas** [comment]
my 20-cents:

- IMO, by far the most important completion is on field members.  

 I think having it JUST for "Standard Metadata" would leave a very incomplete experience (honestly, it would almost seem broken).

I understand the challenge of adding a dependency on Custom Object metadata.  Implementing it in a way that would allow it to still be used in different contexts would required careful planning. 

One solution might be to inject a "FieldProvider" into the initialization of the LSP.  The would allow the source of the Field completions to be flexible (EG: direct connection to an org vs parsing local `-meta.xml` vs using generated "proxy" classes).  The Interface might be as simple as something like this:

``` ts
provideFields(sObject: string): FieldMember[] 

type FieldMember = BasicFieldMember | ReferenceFieldMember;

interface BasicFieldMember {
    apiName: string;
    type: 'text' | 'long-text' | 'number' | 'boolean';
}

interface ReferenceFieldMember {
   apiName: string;
   type: 'parent' | 'child';
   referencedSObject: string;   // api name
}
```

- After Field completion, I think functions and literals completion would be second most valuable.

- Benefits from keyword completion seem minimal.

- where/having value type checking would be cool, but I can't imagine it really saving much productivity.

**Comment by praksb** [comment]
@ChuckJonas At least in the first release for this feature we will be supporting SOQL completion only in Apex scenarios, we are planning to gather SObject types to show for completion from the generated proxy classes which includes BOTH standard objects as well as custom objects. These files currently include the field members as well which we will be using. For this to work properly, the list of SObjects locally needs to be up to date and the user should run the command "Refresh SObject Definitions".

Can you clarify what you mean by literals completion?

We will have some support for keyword completion also. Value type checking or any other semantic validation is not possible at this point since the client side compiler support for SOQL is very minimal and limited mostly to syntax analysis only. This is something we will continue to work on and have sometime in the future.

**Comment by ChuckJonas** [comment]
@praksb glad to hear you'll be supporting custom objects as well!

By literals I mean [stuff like this](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_dateformats.htm)

**Comment by smaddox-sf** [comment]
We have created a basic SOQL language server.  You can try it out by downloading the new SOQL Builder extension https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode-soql.  The language server still has a ways to go and we'll be continuing to iterate and bake it into Apex
