### ISSUE TITLE
nodePath assigned in workspace settings

### ISSUE THREAD

**Issue by celador** [forcedotcom/salesforcedx-vscode#985]
When I installed salesforce.salesforcedx-vscode-lwc it added the following setting to my workspace settings ` "eslint.nodePath": "/Users/john/.vscode/extensions/salesforce.salesforcedx-vscode-lwc-44.17.0/node_modules"` .  

Eslint broke for my project and all the subfolders.  I spent much of the last couple days troubleshooting the issue.

**Comment by timothywlewis** [comment]
We are not using eslint in our project but this is also causing us friction. Our project's .code-workspace files are committed to git so they can be shared across our team but now the vscode plugin is adding this "eslint.nodePath" setting which has a machine-dependent path which just mucks up the whole git commit process. This is an issue since we expect the .code-workspace files to remain machine agnostic.
